CURRENT_LINKER_VERSION = "feature.linker.current_version"
REF_CACHE_LIMIT_KEY = "feature.text.ref_cache_limit"
ENABLE_WEBPAGES = "feature.webpages.enable"
CLIENT_REMOTE_CONFIG_JSON = "feature.client.remote_config_json"
EXPIRE_LEGACY_COOKIES = "feature.cookies.expire_legacy"