# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-05-14 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='user_type',
            field=models.CharField(choices=[('Monastic', 'Monastic'), ('Teacher', 'Teacher'), ('Student', 'Student'), ('Educated* /Dr / Prof', 'Educated* /Dr / Prof'), ('Plan creator', 'Plan creator'), ('regular user', 'regular user'), ('Reader', 'Reader')], max_length=20),
        ),
    ]
