version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - cache
      - postgres

  db:
    image: "mongo:4.4"
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

  cache:
    image: "redis:latest"
    ports:
      - "6379:6379"

  node:
    image: "node:latest"
    working_dir: /app
    volumes:
      - .:/app
    command: npm start
    ports:
      - "3000:3000"

  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: sefaria
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/sefaria_data

volumes:
  mongo-data:
  postgres-data:
