version: '3'

services:
  web:
    build:
      context: .
      dockerfile: dev_docker/Dockerfile
    ports:
      - "8001:8000"
    networks:
      - default
    command: >
      sh -c "
      npm install &&
      npm run build &&
      python manage.py migrate sites &&
      python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    restart: unless-stopped
