#!/usr/bin/env bash
# Run a python script with necessary setup

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

export PYTHONPATH=$DIR
export DJANGO_SETTINGS_MODULE=sefaria.settings

if [ $# -eq 0 ]; then
    echo "Please specify a python script to run."
    exit 1
fi

if [ "$1" = "--profile" ] ; then
    profilescript=true
    shift
fi

# look in scripts/ by default
if [ -e $DIR/scripts/$1 ]; then
    script="$DIR/scripts/$1"
else
    script=$1
fi

if [ $# -eq 1 ]; then
    if [ "$profilescript" = true ] ; then
        echo "profiling"
        python -m cProfile $script
    else
        python $script
    fi
elif [ $# -ge 2 ]; then
    passargs=("${@:2}")
    if [ "$profilescript" = true ] ; then
        echo "profiling"
        python -m cProfile $script "${passargs[@]}"
    else
        python $script "${passargs[@]}"
    fi
fi
