#!/usr/bin/env bash

#py.test tests
py.test -v -m 'not deep and not failing'
PYTEST_RESULTS=$?

#Django API tests
python manage.py test reader -v 2
API_RESULTS=$?

if [ $PYTEST_RESULTS != 0 ] 
then
	echo "py.test failed"
fi

if [ $API_RESULTS != 0 ]
	then
	echo "Django API tests failed"
fi

if [ $API_RESULTS != 0 ] || [ $PYTEST_RESULTS != 0 ]
then
	exit 1
else
	echo "All tests passed!"
	exit 0
fi
