# Generated by OrchestKit Claude Plugin
# Created: 2026-07-14

"""
API-level tests for the community book upload flow (api/community_books.py).

These cover the correctness defects found in the 2026-07-14 audit:
  - the rate-limit bypass (upload() never re-checked at confirm() time)
  - the dead rollback (is_resubmission computed after the Index was already saved)
  - malformed/renamed-zip archives 500ing instead of returning 400
  - admin scope on approve()/reject() (staff-only, no self-approval guard)
  - the moderation gap: a non-approved community book is readable by anyone

Named `community_books_test.py` (not `test_community_books.py`) because
sefaria/pytest.ini only collects `reader/tests/*_test.py` — the parser test's
`test_community_book_parser.py` name is exactly why that suite silently never ran.
"""
import io
import json
import uuid
import zipfile
from datetime import datetime, timedelta
from unittest import mock

from django.contrib.auth.models import User
from django.core.files.uploadedfile import SimpleUploadedFile
from django.test import TestCase

from api import community_books as cb_views
from api.community_books import CommunityBookStatus, can_view_community_book
from sefaria.helper.community_book_parser import Chapter, ParseResult
from sefaria.model import Index, Version, VersionState, Ref, library
from sefaria.search import TextIndexer
from sefaria.system.database import db


def _fake_parse_result():
    chapter = Chapter(title="Chapter One", sections=[], content=["Some body text."], word_count=3)
    return ParseResult(chapters=[chapter], total_words=3, structure_depth=1)


def _upload_kwargs(**overrides):
    token = uuid.uuid4().hex
    kwargs = {
        "file": SimpleUploadedFile("book.docx", b"PK\x03\x04fake docx bytes", content_type="application/octet-stream"),
        "title_en": f"Test Community Book {token}",
        # A distinct Hebrew title, not the empty-string default: build_schema falls
        # back to title_en for title_he when this is blank, which makes the title
        # group's en/he entries identical text and trips an unrelated pre-existing
        # "duplicate titles in this object's title group" validation in
        # sefaria/model/schema.py — not one of the defects this test file covers.
        "title_he": f"ספר קהילה לבדיקה {token}",
        "language": "en",
        "description_en": "A test book",
        "description_he": "",
        "depth": "1",
        "license": "CC-BY",
        "topics": json.dumps([{"asTyped": "Torah", "slug": "torah"}]),
    }
    kwargs.update(overrides)
    return kwargs


class CommunityBooksApiTestBase(TestCase):
    databases = "__all__"

    def setUp(self):
        token = uuid.uuid4().hex
        self.user = User.objects.create_user(
            username=f"cb-user-{token}", email=f"cb-user-{token}@example.com", password="password",
        )
        self.other_user = User.objects.create_user(
            username=f"cb-other-{token}", email=f"cb-other-{token}@example.com", password="password",
        )
        self.admin_user = User.objects.create_user(
            username=f"cb-admin-{token}", email=f"cb-admin-{token}@example.com", password="password",
        )
        self._created_titles = []

    def tearDown(self):
        for title in self._created_titles:
            idx = Index().load({"title": title})
            if idx:
                idx.delete()
            db.texts.delete_many({"title": title})
            db.vstate.delete_many({"title": title})

    def _track(self, title):
        self._created_titles.append(title)
        return title

    def _mocked_gcs(self):
        patches = [
            mock.patch.object(cb_views.GoogleStorageManager, "upload_file", return_value="https://fake-gcs/fake.docx"),
            mock.patch.object(cb_views.GoogleStorageManager, "get_filename", return_value=io.BytesIO(b"fake")),
        ]
        for p in patches:
            p.start()
            self.addCleanup(p.stop)

    def _mocked_parser(self):
        p = mock.patch.object(cb_views, "parse_document", return_value=_fake_parse_result())
        p.start()
        self.addCleanup(p.stop)

class AuthRequiredTests(CommunityBooksApiTestBase):
    def test_upload_requires_authentication(self):
        response = self.client.post("/api/community-books/upload", data=_upload_kwargs())
        self.assertEqual(response.status_code, 401)

    def test_confirm_requires_authentication(self):
        response = self.client.post(
            "/api/community-books/confirm",
            data=json.dumps({"upload_token": "bogus"}),
            content_type="application/json",
        )
        self.assertEqual(response.status_code, 401)


class RateLimitBypassTests(CommunityBooksApiTestBase):
    @mock.patch.object(cb_views, "MAX_DAILY_SUBMISSIONS", 1)
    def test_confirm_re_checks_rate_limit_after_upload_issued_extra_tokens(self):
        self._mocked_gcs()
        self._mocked_parser()
        self.client.force_login(self.user)

        upload_resp_1 = self.client.post("/api/community-books/upload", data=_upload_kwargs())
        upload_resp_2 = self.client.post("/api/community-books/upload", data=_upload_kwargs())
        self.assertEqual(upload_resp_1.status_code, 200)
        self.assertEqual(upload_resp_2.status_code, 200)  # bypass: upload() alone never sees the count grow

        token_1 = json.loads(upload_resp_1.content)["upload_token"]
        token_2 = json.loads(upload_resp_2.content)["upload_token"]

        from django.core import signing
        title_1 = signing.loads(token_1, salt="community-book-upload")["title_en"]
        title_2 = signing.loads(token_2, salt="community-book-upload")["title_en"]
        self._track(title_1)
        self._track(title_2)

        confirm_resp_1 = self.client.post(
            "/api/community-books/confirm", data=json.dumps({"upload_token": token_1}), content_type="application/json",
        )
        self.assertEqual(confirm_resp_1.status_code, 201, confirm_resp_1.content)

        confirm_resp_2 = self.client.post(
            "/api/community-books/confirm", data=json.dumps({"upload_token": token_2}), content_type="application/json",
        )
        self.assertEqual(confirm_resp_2.status_code, 429, confirm_resp_2.content)
        self.assertIsNone(Index().load({"title": title_2}))


class OrphanIndexRollbackTests(CommunityBooksApiTestBase):
    def test_version_save_failure_does_not_leave_orphaned_index(self):
        self._mocked_gcs()
        self._mocked_parser()
        self.client.force_login(self.user)

        upload_resp = self.client.post("/api/community-books/upload", data=_upload_kwargs())
        self.assertEqual(upload_resp.status_code, 200)
        token = json.loads(upload_resp.content)["upload_token"]

        from django.core import signing
        title = signing.loads(token, salt="community-book-upload")["title_en"]
        self._track(title)

        with mock.patch.object(cb_views.Version, "save", side_effect=RuntimeError("boom")):
            confirm_resp = self.client.post(
                "/api/community-books/confirm", data=json.dumps({"upload_token": token}), content_type="application/json",
            )

        self.assertEqual(confirm_resp.status_code, 500, confirm_resp.content)
        self.assertIsNone(
            Index().load({"title": title}),
            "Version.save() failure on a first-time submission must not leave a contentless Index behind",
        )


class MalformedArchiveTests(CommunityBooksApiTestBase):
    def _fake_docx_bytes(self):
        # A real zip (so DOCX_MAGIC + the file-under-test's zip check pass) but
        # missing the Office parts python-docx needs -> PackageNotFoundError/BadZipFile/KeyError,
        # none of which is a ParseError.
        buf = io.BytesIO()
        with zipfile.ZipFile(buf, "w") as zf:
            zf.writestr("not_a_docx_part.txt", "hello")
        return buf.getvalue()

    def test_malformed_archive_on_upload_returns_400_not_500(self):
        self.client.force_login(self.user)
        bad_file = SimpleUploadedFile("book.docx", self._fake_docx_bytes(), content_type="application/octet-stream")
        response = self.client.post("/api/community-books/upload", data=_upload_kwargs(file=bad_file))
        self.assertEqual(response.status_code, 400, response.content)

    def test_malformed_archive_on_confirm_returns_400_not_500(self):
        self._mocked_gcs()
        self.client.force_login(self.user)

        # Upload succeeds with a mocked parser (so we can reach confirm()); confirm()
        # re-parses the file it fetches from GCS, which we make return the bad bytes.
        with mock.patch.object(cb_views, "parse_document", return_value=_fake_parse_result()):
            upload_resp = self.client.post("/api/community-books/upload", data=_upload_kwargs())
        self.assertEqual(upload_resp.status_code, 200)
        token = json.loads(upload_resp.content)["upload_token"]

        from django.core import signing
        title = signing.loads(token, salt="community-book-upload")["title_en"]
        self._track(title)

        with mock.patch.object(
            cb_views.GoogleStorageManager, "get_filename", return_value=io.BytesIO(self._fake_docx_bytes())
        ):
            confirm_resp = self.client.post(
                "/api/community-books/confirm", data=json.dumps({"upload_token": token}), content_type="application/json",
            )
        self.assertEqual(confirm_resp.status_code, 400, confirm_resp.content)


class AdminScopeTests(CommunityBooksApiTestBase):
    def _submitted_book(self, submitter):
        title = self._track(f"Admin Scope Book {uuid.uuid4().hex}")
        idx = Index({
            "title": title,
            "categories": ["Community"],
            "schema": {
                "nodeType": "JaggedArrayNode", "depth": 1, "addressTypes": ["Integer"],
                "sectionNames": ["Chapter"], "key": title, "titles": [
                    {"lang": "en", "text": title, "primary": True},
                    {"lang": "he", "text": f"{title} (he)", "primary": True},
                ],
            },
            "communityBook": {
                "status": CommunityBookStatus.SUBMITTED,
                "submittedBy": submitter.id,
                "submittedAt": datetime.utcnow(),
                "reviewedBy": None,
                "rejectionReason": None,
                "topics": [],
            },
            "hidden": True,
            "enDesc": "desc",
            "heDesc": "",
        })
        idx.save(override_dependencies=True)
        return title

    def test_non_admin_cannot_approve(self):
        original = list(cb_views.COMMUNITY_BOOK_ADMIN_IDS)
        cb_views.COMMUNITY_BOOK_ADMIN_IDS[:] = []
        self.addCleanup(lambda: cb_views.COMMUNITY_BOOK_ADMIN_IDS.__setitem__(slice(None), original))

        title = self._submitted_book(self.other_user)
        self.client.force_login(self.user)  # not in COMMUNITY_BOOK_ADMIN_IDS
        response = self.client.post(f"/api/community-books/{title}/approve")
        self.assertEqual(response.status_code, 403, response.content)
        idx = Index().load({"title": title})
        self.assertEqual(idx.communityBook["status"], CommunityBookStatus.SUBMITTED)

    def test_admin_cannot_approve_own_submission(self):
        title = self._submitted_book(self.admin_user)
        original = list(cb_views.COMMUNITY_BOOK_ADMIN_IDS)
        cb_views.COMMUNITY_BOOK_ADMIN_IDS[:] = [self.admin_user.id]
        self.addCleanup(lambda: cb_views.COMMUNITY_BOOK_ADMIN_IDS.__setitem__(slice(None), original))

        self.client.force_login(self.admin_user)
        response = self.client.post(f"/api/community-books/{title}/approve")
        self.assertEqual(response.status_code, 403, response.content)
        idx = Index().load({"title": title})
        self.assertEqual(idx.communityBook["status"], CommunityBookStatus.SUBMITTED)

    def test_admin_can_approve_someone_elses_submission(self):
        title = self._submitted_book(self.other_user)
        original = list(cb_views.COMMUNITY_BOOK_ADMIN_IDS)
        cb_views.COMMUNITY_BOOK_ADMIN_IDS[:] = [self.admin_user.id]
        self.addCleanup(lambda: cb_views.COMMUNITY_BOOK_ADMIN_IDS.__setitem__(slice(None), original))

        self.client.force_login(self.admin_user)
        response = self.client.post(f"/api/community-books/{title}/approve")
        self.assertEqual(response.status_code, 200, response.content)
        idx = Index().load({"title": title})
        self.assertEqual(idx.communityBook["status"], CommunityBookStatus.APPROVED)


class ModerationGapHelperTests(TestCase):
    """
    Unit tests for can_view_community_book(), the narrow helper used to gate
    reads of non-approved community books. See ReadGateTests below for
    request-level tests confirming it is wired into reader/views.py's
    texts_api and catchall.
    """

    class _FakeUser:
        def __init__(self, id=None, authenticated=True):
            self.id = id
            self.is_authenticated = authenticated

    class _FakeIndex:
        def __init__(self, community_book):
            self.communityBook = community_book

        @property
        def is_community_book(self):
            return self.communityBook is not None

    def test_approved_book_visible_to_anyone(self):
        idx = self._FakeIndex({"status": CommunityBookStatus.APPROVED, "submittedBy": 1})
        anon = self._FakeUser(authenticated=False)
        stranger = self._FakeUser(id=999)
        self.assertTrue(can_view_community_book(idx, anon))
        self.assertTrue(can_view_community_book(idx, stranger))

    def test_submitted_book_visible_only_to_submitter_or_admin(self):
        idx = self._FakeIndex({"status": CommunityBookStatus.SUBMITTED, "submittedBy": 1})
        submitter = self._FakeUser(id=1)
        stranger = self._FakeUser(id=2)
        anon = self._FakeUser(authenticated=False)

        self.assertTrue(can_view_community_book(idx, submitter))
        self.assertFalse(can_view_community_book(idx, stranger))
        self.assertFalse(can_view_community_book(idx, anon))

    def test_rejected_book_visible_to_admin_but_not_stranger(self):
        original = list(cb_views.COMMUNITY_BOOK_ADMIN_IDS)
        cb_views.COMMUNITY_BOOK_ADMIN_IDS[:] = [42]
        try:
            idx = self._FakeIndex({"status": CommunityBookStatus.REJECTED, "submittedBy": 1})
            admin = self._FakeUser(id=42)
            stranger = self._FakeUser(id=2)
            self.assertTrue(can_view_community_book(idx, admin))
            self.assertFalse(can_view_community_book(idx, stranger))
        finally:
            cb_views.COMMUNITY_BOOK_ADMIN_IDS[:] = original

    def test_non_community_book_always_visible(self):
        idx = self._FakeIndex(None)
        anon = self._FakeUser(authenticated=False)
        self.assertTrue(can_view_community_book(idx, anon))


class ReadGateTests(CommunityBooksApiTestBase):
    """
    Request-level tests confirming can_view_community_book() is actually wired
    into reader/views.py's texts_api, via the Django test client.
    """

    def _make_book(self, submitter, status=CommunityBookStatus.SUBMITTED, with_version=True):
        title = self._track(f"Read Gate Book {uuid.uuid4().hex}")
        idx = Index({
            "title": title,
            "categories": ["Community"],
            "schema": {
                "nodeType": "JaggedArrayNode", "depth": 1, "addressTypes": ["Integer"],
                "sectionNames": ["Chapter"], "key": title, "titles": [
                    {"lang": "en", "text": title, "primary": True},
                    {"lang": "he", "text": f"{title} (he)", "primary": True},
                ],
            },
            "communityBook": {
                "status": status,
                "submittedBy": submitter.id,
                "submittedAt": datetime.utcnow(),
                "reviewedBy": None,
                "rejectionReason": "Not a good fit" if status == CommunityBookStatus.REJECTED else None,
                "topics": [],
            },
            "hidden": status != CommunityBookStatus.APPROVED,
            "enDesc": "desc",
            "heDesc": "",
        })
        idx.save()
        if with_version:
            Version({
                "title": title,
                "language": "en",
                "versionTitle": f"Test Version {uuid.uuid4().hex}",
                "versionSource": "https://example.com",
                "chapter": ["Some content."],
                "actualLanguage": "en",
                "isSource": True,
                "isPrimary": True,
                "direction": "ltr",
            }).save()
        return title

    def _get_text(self, title):
        return self.client.get(f"/api/texts/{title.replace(' ', '_')}")

    def test_third_party_gets_404_on_submitted_book(self):
        title = self._make_book(self.user, status=CommunityBookStatus.SUBMITTED)
        self.client.force_login(self.other_user)
        response = self._get_text(title)
        self.assertEqual(response.status_code, 404)

    def test_submitter_gets_200_on_own_submitted_book(self):
        title = self._make_book(self.user, status=CommunityBookStatus.SUBMITTED)
        self.client.force_login(self.user)
        response = self._get_text(title)
        self.assertEqual(response.status_code, 200, response.content)

    def test_admin_gets_200_on_submitted_book(self):
        title = self._make_book(self.other_user, status=CommunityBookStatus.SUBMITTED)
        original = list(cb_views.COMMUNITY_BOOK_ADMIN_IDS)
        cb_views.COMMUNITY_BOOK_ADMIN_IDS[:] = [self.admin_user.id]
        self.addCleanup(lambda: cb_views.COMMUNITY_BOOK_ADMIN_IDS.__setitem__(slice(None), original))

        self.client.force_login(self.admin_user)
        response = self._get_text(title)
        self.assertEqual(response.status_code, 200, response.content)

    def test_third_party_gets_200_once_approved(self):
        title = self._make_book(self.user, status=CommunityBookStatus.APPROVED)
        self.client.force_login(self.other_user)
        response = self._get_text(title)
        self.assertEqual(response.status_code, 200, response.content)

    def test_third_party_gets_404_on_rejected_book(self):
        title = self._make_book(self.user, status=CommunityBookStatus.REJECTED)
        self.client.force_login(self.other_user)
        response = self._get_text(title)
        self.assertEqual(response.status_code, 404)


class _FakeCommunityBookIndex:
    def __init__(self, title, status):
        self.title = title
        self.communityBook = {"status": status} if status is not None else None

    @property
    def is_community_book(self):
        return self.communityBook is not None

    def best_time_period(self):
        class _TP:
            start = 0
        return _TP()


class _FakeCommunityBookVersion:
    def __init__(self, title, vt, lang, status):
        self.title = title
        self.versionTitle = vt
        self.language = lang
        self._index = _FakeCommunityBookIndex(title, status)

    def get_index(self):
        return self._index


class SearchIndexingExclusionTests(TestCase):
    """
    Exercises TextIndexer.index_all()'s decision of whether to index a given
    index/version, using fake Index/Version objects in place of real
    Elasticsearch and Mongo I/O (matching the pattern already used in
    sefaria/tests/search_test.py). This does NOT exercise real Elasticsearch
    indexing -- it verifies the decision predicate that gates entry into the
    per-version indexing call.
    """

    def test_non_approved_community_book_excluded_approved_included(self):
        submitted_v = _FakeCommunityBookVersion("Submitted Book", "v1", "en", CommunityBookStatus.SUBMITTED)
        rejected_v = _FakeCommunityBookVersion("Rejected Book", "v1", "en", CommunityBookStatus.REJECTED)
        approved_v = _FakeCommunityBookVersion("Approved Book", "v1", "en", CommunityBookStatus.APPROVED)
        non_community_v = _FakeCommunityBookVersion("Regular Book", "v1", "en", None)
        all_versions = [submitted_v, rejected_v, approved_v, non_community_v]

        TextIndexer._failed_versions = []
        TextIndexer._skipped_versions = []
        TextIndexer._bulk_actions = []

        indexed_titles = []

        def fake_index_version(cls, version, tries=0, action=None):
            indexed_titles.append(version.title)

        with mock.patch.object(TextIndexer, "create_version_priority_map", classmethod(lambda cls: None)), \
             mock.patch.object(TextIndexer, "create_terms_dict", classmethod(lambda cls: None)), \
             mock.patch.object(TextIndexer, "get_all_versions", classmethod(lambda cls: list(all_versions))), \
             mock.patch.object(TextIndexer, "excluded_from_search", classmethod(lambda cls, v: False)), \
             mock.patch.object(TextIndexer, "index_version", classmethod(fake_index_version)), \
             mock.patch("sefaria.search.Ref.clear_cache", lambda: None), \
             mock.patch.object(TextIndexer, "_flush_bulk_actions", classmethod(lambda cls, versions: 0)):
            TextIndexer.version_priority_map = {
                (v.title, v.versionTitle, v.language): (i, None)
                for i, v in enumerate(all_versions)
            }
            TextIndexer.index_all(index_name="text-b", debug=False, for_es=True)

        self.assertNotIn("Submitted Book", indexed_titles)
        self.assertNotIn("Rejected Book", indexed_titles)
        self.assertIn("Approved Book", indexed_titles)
        self.assertIn("Regular Book", indexed_titles)

        skipped_reasons = {s["title"]: s.get("reason") for s in TextIndexer._skipped_versions}
        self.assertEqual(skipped_reasons.get("Submitted Book"), "community_book_not_approved")
        self.assertEqual(skipped_reasons.get("Rejected Book"), "community_book_not_approved")


class LibraryCacheRegistrationTests(CommunityBooksApiTestBase):
    """
    Guards against a newly created community book being saved with
    override_dependencies=True, which skips the observers that register the
    title in the core library cache and create its VersionState. When that
    happens, Index.save() succeeds and the document exists in Mongo, but
    Ref(title) raises InputError because the running process's in-memory
    title cache never learned about the new book -- the book becomes
    unreachable even though it was "successfully" submitted.
    """

    def test_confirmed_book_is_ref_resolvable_and_has_version_state(self):
        self._mocked_gcs()
        self._mocked_parser()
        self.client.force_login(self.user)

        upload_kwargs = _upload_kwargs()
        upload_resp = self.client.post("/api/community-books/upload", data=upload_kwargs)
        self.assertEqual(upload_resp.status_code, 200, upload_resp.content)
        token = json.loads(upload_resp.content)["upload_token"]

        from django.core import signing
        title = signing.loads(token, salt="community-book-upload")["title_en"]
        self._track(title)

        confirm_resp = self.client.post(
            "/api/community-books/confirm", data=json.dumps({"upload_token": token}), content_type="application/json",
        )
        self.assertEqual(confirm_resp.status_code, 201, confirm_resp.content)

        try:
            ref = Ref(f"{title} 1")
        except Exception as e:
            self.fail(f"Ref({title!r} 1) should resolve for a just-confirmed community book, raised: {e}")
        self.assertEqual(ref.index.title, title)

        vs = VersionState(title)
        self.assertFalse(vs.is_new_state, "VersionState should have been created on Index save")
