# Generated by OrchestKit Claude Plugin
# Created: 2026-07-14

"""
API-level tests for the community book upload flow (api/community_books.py).

These cover the correctness defects found in the 2026-07-14 audit:
  - the rate-limit bypass (upload() never re-checked at confirm() time)
  - the dead rollback (is_resubmission computed after the Index was already saved)
  - malformed/renamed-zip archives 500ing instead of returning 400
  - admin scope on approve()/reject() (staff-only, no self-approval guard)
  - the moderation gap: a non-approved community book is readable by anyone

Named `community_books_test.py` (not `test_community_books.py`) because
sefaria/pytest.ini only collects `reader/tests/*_test.py` — the parser test's
`test_community_book_parser.py` name is exactly why that suite silently never ran.
"""
import io
import json
import re
import itertools
import uuid
import zipfile
from datetime import datetime, timedelta
from unittest import mock

from django.contrib.auth.models import User
from django.core.files.uploadedfile import SimpleUploadedFile
from django.http import Http404, HttpResponse
from django.test import RequestFactory, TestCase

from api import community_books as cb_views
from api.community_books import CommunityBookStatus, can_view_community_book, is_community_book_publicly_readable
from reader import views as reader_views
from sefaria.helper.community_book_parser import Chapter, ParseResult
from sefaria.model import Index, Version, VersionState, Ref, library
from sefaria.search import TextIndexer
from sefaria.system.database import db


# Title prefixes used by every community-book test below. Django's TestCase
# rolls back the SQL users a run creates, but Mongo writes (Index docs) are
# not part of that transaction, so an interrupted run (Ctrl-C, crash,
# timeout) can leave an orphan community-book Index behind. A later run's
# freshly-created SQL users then get reused auto-increment ids, which can
# collide with a leftover doc's `submittedBy` and trip rate-limit/ownership
# logic on the very first upload. Sweeping by these prefixes before (and
# after) the module runs makes the suite self-healing across interruptions.
COMMUNITY_BOOK_TEST_TITLE_PREFIXES = (
    "Test Community Book ",
    "Admin Scope Book ",
    "Read Gate Book ",
)


def _purge_community_book_title(title):
    """Best-effort removal of a community-book Index and its dependent
    documents. Tolerant of partially-created or already-missing state so a
    prior interruption never blocks cleanup here or in a later run."""
    try:
        idx = Index().load({"title": title})
    except Exception:
        idx = None
    if idx:
        try:
            idx.delete()
        except Exception:
            pass
    # Belt-and-suspenders: Index.delete() may not fully clean a malformed
    # leftover doc, so also clear the raw collections directly.
    try:
        db.index.delete_many({"title": title})
        db.texts.delete_many({"title": title})
        db.vstate.delete_many({"title": title})
    except Exception:
        pass


TEST_USER_ID_BASE = 90000000
_test_user_id_counter = itertools.count()


def _sweep_leftover_community_book_titles():
    for prefix in COMMUNITY_BOOK_TEST_TITLE_PREFIXES:
        titles = db.index.distinct("title", {"title": {"$regex": f"^{re.escape(prefix)}"}})
        for title in titles:
            _purge_community_book_title(title)


def setUpModule():
    # Clean up any orphans left by a prior interrupted run before this
    # module's tests execute.
    _sweep_leftover_community_book_titles()


def tearDownModule():
    # Clean up after ourselves too, in case a test in this run gets
    # interrupted before its own tearDown runs.
    _sweep_leftover_community_book_titles()


def _fake_parse_result():
    chapter = Chapter(title="Chapter One", sections=[], content=["Some body text."], word_count=3)
    return ParseResult(chapters=[chapter], total_words=3, structure_depth=1)


def _upload_kwargs(**overrides):
    token = uuid.uuid4().hex
    kwargs = {
        "file": SimpleUploadedFile("book.docx", b"PK\x03\x04fake docx bytes", content_type="application/octet-stream"),
        "title_en": f"Test Community Book {token}",
        # A distinct Hebrew title, not the empty-string default: build_schema falls
        # back to title_en for title_he when this is blank, which makes the title
        # group's en/he entries identical text and trips an unrelated pre-existing
        # "duplicate titles in this object's title group" validation in
        # sefaria/model/schema.py — not one of the defects this test file covers.
        "title_he": f"ספר קהילה לבדיקה {token}",
        "language": "en",
        "description_en": "A test book",
        "description_he": "",
        "depth": "1",
        "license": "CC-BY",
        "topics": json.dumps([{"asTyped": "Torah", "slug": "torah"}]),
    }
    kwargs.update(overrides)
    return kwargs


class CommunityBooksApiTestBase(TestCase):
    databases = "__all__"

    def setUp(self):
        token = uuid.uuid4().hex
        # Django rolls back its SQL users between tests, so auto-increment ids
        # get reused and start at 1. Mongo is not transactional and the dev
        # database already holds community books submitted by low user ids, which
        # would count against a fresh test user's submission limits before it did
        # anything. Pin the test users well above any real id instead, so they are
        # isolated without deleting anyone else's data.
        base_id = TEST_USER_ID_BASE + next(_test_user_id_counter) * 3
        self.user = User.objects.create_user(
            id=base_id,
            username=f"cb-user-{token}", email=f"cb-user-{token}@example.com", password="password",
        )
        self.other_user = User.objects.create_user(
            id=base_id + 1,
            username=f"cb-other-{token}", email=f"cb-other-{token}@example.com", password="password",
        )
        self.admin_user = User.objects.create_user(
            id=base_id + 2,
            username=f"cb-admin-{token}", email=f"cb-admin-{token}@example.com", password="password",
        )
        self._created_titles = []

    def tearDown(self):
        for title in self._created_titles:
            _purge_community_book_title(title)

    def _track(self, title):
        self._created_titles.append(title)
        return title

    def _mocked_gcs(self):
        patches = [
            mock.patch.object(cb_views.GoogleStorageManager, "upload_file", return_value="https://fake-gcs/fake.docx"),
            mock.patch.object(cb_views.GoogleStorageManager, "get_filename", return_value=io.BytesIO(b"fake")),
        ]
        for p in patches:
            p.start()
            self.addCleanup(p.stop)

    def _mocked_parser(self):
        p = mock.patch.object(cb_views, "parse_document", return_value=_fake_parse_result())
        p.start()
        self.addCleanup(p.stop)

class AuthRequiredTests(CommunityBooksApiTestBase):
    def test_upload_requires_authentication(self):
        response = self.client.post("/api/community-books/upload", data=_upload_kwargs())
        self.assertEqual(response.status_code, 401)

    def test_confirm_requires_authentication(self):
        response = self.client.post(
            "/api/community-books/confirm",
            data=json.dumps({"upload_token": "bogus"}),
            content_type="application/json",
        )
        self.assertEqual(response.status_code, 401)


class RateLimitBypassTests(CommunityBooksApiTestBase):
    @mock.patch.object(cb_views, "MAX_DAILY_SUBMISSIONS", 1)
    def test_confirm_re_checks_rate_limit_after_upload_issued_extra_tokens(self):
        self._mocked_gcs()
        self._mocked_parser()
        self.client.force_login(self.user)

        upload_resp_1 = self.client.post("/api/community-books/upload", data=_upload_kwargs())
        upload_resp_2 = self.client.post("/api/community-books/upload", data=_upload_kwargs())
        self.assertEqual(upload_resp_1.status_code, 200)
        self.assertEqual(upload_resp_2.status_code, 200)  # bypass: upload() alone never sees the count grow

        token_1 = json.loads(upload_resp_1.content)["upload_token"]
        token_2 = json.loads(upload_resp_2.content)["upload_token"]

        from django.core import signing
        title_1 = signing.loads(token_1, salt="community-book-upload")["title_en"]
        title_2 = signing.loads(token_2, salt="community-book-upload")["title_en"]
        self._track(title_1)
        self._track(title_2)

        confirm_resp_1 = self.client.post(
            "/api/community-books/confirm", data=json.dumps({"upload_token": token_1}), content_type="application/json",
        )
        self.assertEqual(confirm_resp_1.status_code, 201, confirm_resp_1.content)

        confirm_resp_2 = self.client.post(
            "/api/community-books/confirm", data=json.dumps({"upload_token": token_2}), content_type="application/json",
        )
        self.assertEqual(confirm_resp_2.status_code, 429, confirm_resp_2.content)
        self.assertIsNone(Index().load({"title": title_2}))


class OrphanIndexRollbackTests(CommunityBooksApiTestBase):
    def test_version_save_failure_does_not_leave_orphaned_index(self):
        self._mocked_gcs()
        self._mocked_parser()
        self.client.force_login(self.user)

        upload_resp = self.client.post("/api/community-books/upload", data=_upload_kwargs())
        self.assertEqual(upload_resp.status_code, 200)
        token = json.loads(upload_resp.content)["upload_token"]

        from django.core import signing
        title = signing.loads(token, salt="community-book-upload")["title_en"]
        self._track(title)

        with mock.patch.object(cb_views.Version, "save", side_effect=RuntimeError("boom")):
            confirm_resp = self.client.post(
                "/api/community-books/confirm", data=json.dumps({"upload_token": token}), content_type="application/json",
            )

        self.assertEqual(confirm_resp.status_code, 500, confirm_resp.content)
        self.assertIsNone(
            Index().load({"title": title}),
            "Version.save() failure on a first-time submission must not leave a contentless Index behind",
        )


class MalformedArchiveTests(CommunityBooksApiTestBase):
    def _fake_docx_bytes(self):
        # A real zip (so DOCX_MAGIC + the file-under-test's zip check pass) but
        # missing the Office parts python-docx needs -> PackageNotFoundError/BadZipFile/KeyError,
        # none of which is a ParseError.
        buf = io.BytesIO()
        with zipfile.ZipFile(buf, "w") as zf:
            zf.writestr("not_a_docx_part.txt", "hello")
        return buf.getvalue()

    def test_malformed_archive_on_upload_returns_400_not_500(self):
        self.client.force_login(self.user)
        bad_file = SimpleUploadedFile("book.docx", self._fake_docx_bytes(), content_type="application/octet-stream")
        response = self.client.post("/api/community-books/upload", data=_upload_kwargs(file=bad_file))
        self.assertEqual(response.status_code, 400, response.content)

    def test_malformed_archive_on_confirm_returns_400_not_500(self):
        self._mocked_gcs()
        self.client.force_login(self.user)

        # Upload succeeds with a mocked parser (so we can reach confirm()); confirm()
        # re-parses the file it fetches from GCS, which we make return the bad bytes.
        with mock.patch.object(cb_views, "parse_document", return_value=_fake_parse_result()):
            upload_resp = self.client.post("/api/community-books/upload", data=_upload_kwargs())
        self.assertEqual(upload_resp.status_code, 200)
        token = json.loads(upload_resp.content)["upload_token"]

        from django.core import signing
        title = signing.loads(token, salt="community-book-upload")["title_en"]
        self._track(title)

        with mock.patch.object(
            cb_views.GoogleStorageManager, "get_filename", return_value=io.BytesIO(self._fake_docx_bytes())
        ):
            confirm_resp = self.client.post(
                "/api/community-books/confirm", data=json.dumps({"upload_token": token}), content_type="application/json",
            )
        self.assertEqual(confirm_resp.status_code, 400, confirm_resp.content)


class AdminScopeTests(CommunityBooksApiTestBase):
    def _submitted_book(self, submitter):
        title = self._track(f"Admin Scope Book {uuid.uuid4().hex}")
        idx = Index({
            "title": title,
            "categories": ["Community"],
            "schema": {
                "nodeType": "JaggedArrayNode", "depth": 1, "addressTypes": ["Integer"],
                "sectionNames": ["Chapter"], "key": title, "titles": [
                    {"lang": "en", "text": title, "primary": True},
                    {"lang": "he", "text": f"{title} (he)", "primary": True},
                ],
            },
            "communityBook": {
                "status": CommunityBookStatus.SUBMITTED,
                "submittedBy": submitter.id,
                "submittedAt": datetime.utcnow(),
                "reviewedBy": None,
                "rejectionReason": None,
                "topics": [],
            },
            "hidden": True,
            "enDesc": "desc",
            "heDesc": "",
        })
        idx.save(override_dependencies=True)
        return title

    def test_non_admin_cannot_approve(self):
        original = list(cb_views.COMMUNITY_BOOK_ADMIN_IDS)
        cb_views.COMMUNITY_BOOK_ADMIN_IDS[:] = []
        self.addCleanup(lambda: cb_views.COMMUNITY_BOOK_ADMIN_IDS.__setitem__(slice(None), original))

        title = self._submitted_book(self.other_user)
        self.client.force_login(self.user)  # not in COMMUNITY_BOOK_ADMIN_IDS
        response = self.client.post(f"/api/community-books/{title}/approve")
        self.assertEqual(response.status_code, 403, response.content)
        idx = Index().load({"title": title})
        self.assertEqual(idx.communityBook["status"], CommunityBookStatus.SUBMITTED)

    def test_admin_cannot_approve_own_submission(self):
        title = self._submitted_book(self.admin_user)
        original = list(cb_views.COMMUNITY_BOOK_ADMIN_IDS)
        cb_views.COMMUNITY_BOOK_ADMIN_IDS[:] = [self.admin_user.id]
        self.addCleanup(lambda: cb_views.COMMUNITY_BOOK_ADMIN_IDS.__setitem__(slice(None), original))

        self.client.force_login(self.admin_user)
        response = self.client.post(f"/api/community-books/{title}/approve")
        self.assertEqual(response.status_code, 403, response.content)
        idx = Index().load({"title": title})
        self.assertEqual(idx.communityBook["status"], CommunityBookStatus.SUBMITTED)

    def test_admin_can_approve_someone_elses_submission(self):
        title = self._submitted_book(self.other_user)
        original = list(cb_views.COMMUNITY_BOOK_ADMIN_IDS)
        cb_views.COMMUNITY_BOOK_ADMIN_IDS[:] = [self.admin_user.id]
        self.addCleanup(lambda: cb_views.COMMUNITY_BOOK_ADMIN_IDS.__setitem__(slice(None), original))

        self.client.force_login(self.admin_user)
        response = self.client.post(f"/api/community-books/{title}/approve")
        self.assertEqual(response.status_code, 200, response.content)
        idx = Index().load({"title": title})
        self.assertEqual(idx.communityBook["status"], CommunityBookStatus.APPROVED)


class ModerationGapHelperTests(TestCase):
    """
    Unit tests for can_view_community_book(), the per-user helper used to gate
    reads of non-approved community books on the UNCACHED HTML reader path
    only. See ReadGateTests below for request-level tests confirming it is
    wired into reader/views.py's catchall, and confirming the separate,
    strict, all-or-nothing is_community_book_publicly_readable() is wired
    into the Varnish-cached texts_api and index_api paths instead.
    """

    class _FakeUser:
        def __init__(self, id=None, authenticated=True):
            self.id = id
            self.is_authenticated = authenticated

    class _FakeIndex:
        def __init__(self, community_book):
            self.communityBook = community_book

        @property
        def is_community_book(self):
            return self.communityBook is not None

    def test_approved_book_visible_to_anyone(self):
        idx = self._FakeIndex({"status": CommunityBookStatus.APPROVED, "submittedBy": 1})
        anon = self._FakeUser(authenticated=False)
        stranger = self._FakeUser(id=999)
        self.assertTrue(can_view_community_book(idx, anon))
        self.assertTrue(can_view_community_book(idx, stranger))

    def test_submitted_book_visible_only_to_submitter_or_admin(self):
        idx = self._FakeIndex({"status": CommunityBookStatus.SUBMITTED, "submittedBy": 1})
        submitter = self._FakeUser(id=1)
        stranger = self._FakeUser(id=2)
        anon = self._FakeUser(authenticated=False)

        self.assertTrue(can_view_community_book(idx, submitter))
        self.assertFalse(can_view_community_book(idx, stranger))
        self.assertFalse(can_view_community_book(idx, anon))

    def test_rejected_book_visible_to_admin_but_not_stranger(self):
        original = list(cb_views.COMMUNITY_BOOK_ADMIN_IDS)
        cb_views.COMMUNITY_BOOK_ADMIN_IDS[:] = [42]
        try:
            idx = self._FakeIndex({"status": CommunityBookStatus.REJECTED, "submittedBy": 1})
            admin = self._FakeUser(id=42)
            stranger = self._FakeUser(id=2)
            self.assertTrue(can_view_community_book(idx, admin))
            self.assertFalse(can_view_community_book(idx, stranger))
        finally:
            cb_views.COMMUNITY_BOOK_ADMIN_IDS[:] = original

    def test_non_community_book_always_visible(self):
        idx = self._FakeIndex(None)
        anon = self._FakeUser(authenticated=False)
        self.assertTrue(can_view_community_book(idx, anon))


class StrictPublicReadGateHelperTests(TestCase):
    """
    Unit tests for is_community_book_publicly_readable(), the strict,
    user-agnostic helper for read paths Varnish caches keyed on URL alone
    (cookies stripped, so Django never sees who is asking). Unlike
    can_view_community_book(), this must have NO submitter/admin branch --
    a non-approved book is 404 for everyone on these paths, since a 200
    here would be cached and replayed to every subsequent anonymous
    visitor of that URL.
    """

    class _FakeIndex:
        def __init__(self, community_book):
            self.communityBook = community_book

        @property
        def is_community_book(self):
            return self.communityBook is not None

    def test_approved_book_is_publicly_readable(self):
        idx = self._FakeIndex({"status": CommunityBookStatus.APPROVED, "submittedBy": 1})
        self.assertTrue(is_community_book_publicly_readable(idx))

    def test_submitted_book_is_not_publicly_readable_even_for_its_submitter(self):
        # No per-user branch: this helper takes no user argument at all, so
        # there is no way for a submitter to be let through on this path.
        idx = self._FakeIndex({"status": CommunityBookStatus.SUBMITTED, "submittedBy": 1})
        self.assertFalse(is_community_book_publicly_readable(idx))

    def test_rejected_book_is_not_publicly_readable(self):
        idx = self._FakeIndex({"status": CommunityBookStatus.REJECTED, "submittedBy": 1})
        self.assertFalse(is_community_book_publicly_readable(idx))

    def test_non_community_book_always_publicly_readable(self):
        idx = self._FakeIndex(None)
        self.assertTrue(is_community_book_publicly_readable(idx))


class ReadGateTests(CommunityBooksApiTestBase):
    """
    Request-level tests confirming the two read gates are wired into the
    right places in reader/views.py, via the Django test client:

    - texts_api (GET) and index_api (GET, which serves /api/index,
      /api/v2/index, and /api/v2/raw/index) are Varnish-cached, cookie-
      stripped API paths (see helm-chart/sefaria/templates/configmap/
      varnish-config.yaml). Django can never distinguish the submitter from
      an anonymous stranger there, and a 200 would be cached and replayed to
      every subsequent anonymous visitor of that URL. So a non-approved
      community book must be 404 for EVERYONE on these paths, including its
      own submitter -- there is intentionally no per-user exception here.
    - catchall (the HTML reader page, an uncached path) uses the per-user
      can_view_community_book(), where letting the submitter/admin through
      is safe because it never gets cached for anyone else.
    """

    def setUp(self):
        super().setUp()
        self.factory = RequestFactory()

    def _make_book(self, submitter, status=CommunityBookStatus.SUBMITTED, with_version=True):
        title = self._track(f"Read Gate Book {uuid.uuid4().hex}")
        idx = Index({
            "title": title,
            "categories": ["Community"],
            "schema": {
                "nodeType": "JaggedArrayNode", "depth": 1, "addressTypes": ["Integer"],
                "sectionNames": ["Chapter"], "key": title, "titles": [
                    {"lang": "en", "text": title, "primary": True},
                    {"lang": "he", "text": f"{title} (he)", "primary": True},
                ],
            },
            "communityBook": {
                "status": status,
                "submittedBy": submitter.id,
                "submittedAt": datetime.utcnow(),
                "reviewedBy": None,
                "rejectionReason": "Not a good fit" if status == CommunityBookStatus.REJECTED else None,
                "topics": [],
            },
            "hidden": status != CommunityBookStatus.APPROVED,
            "enDesc": "desc",
            "heDesc": "",
        })
        idx.save()
        if with_version:
            Version({
                "title": title,
                "language": "en",
                "versionTitle": f"Test Version {uuid.uuid4().hex}",
                "versionSource": "https://example.com",
                "chapter": ["Some content."],
                "actualLanguage": "en",
                "isSource": True,
                "isPrimary": True,
                "direction": "ltr",
            }).save()
        return title

    def _get_text(self, title):
        return self.client.get(f"/api/texts/{title.replace(' ', '_')}")

    def _get_index(self, title):
        return self.client.get(f"/api/v2/index/{title.replace(' ', '_')}")

    def _catchall_request(self, title, user):
        # Build a request for reader.views.catchall() directly via
        # RequestFactory instead of self.client, and call the view function
        # ourselves. This avoids ever reaching text_panels()'s full-page
        # template render, which requires a webpack build
        # (node/webpack-stats.client.json) that does not exist in this
        # environment -- and shouldn't be required just to test an
        # authorization decision. It also makes this block dramatically
        # faster than the self.client-based version it replaces.
        tref = f"{title.replace(' ', '_')}.1"
        request = self.factory.get(f"/{tref}")
        request.user = user
        return request, tref

    # --- Cached API path (texts_api GET): all-or-nothing, no per-user exception ---

    def test_third_party_gets_404_from_text_api_on_submitted_book(self):
        title = self._make_book(self.user, status=CommunityBookStatus.SUBMITTED)
        self.client.force_login(self.other_user)
        response = self._get_text(title)
        self.assertEqual(response.status_code, 404)

    def test_submitter_gets_404_from_text_api_on_own_submitted_book(self):
        # The cached API path can't tell submitter from stranger (Varnish
        # strips cookies and caches by URL alone), so even the submitter
        # must be denied here -- letting them through would mean caching a
        # 200 with the book's full text and serving it to the public.
        title = self._make_book(self.user, status=CommunityBookStatus.SUBMITTED)
        self.client.force_login(self.user)
        response = self._get_text(title)
        self.assertEqual(response.status_code, 404, response.content)

    def test_admin_gets_404_from_text_api_on_submitted_book(self):
        title = self._make_book(self.other_user, status=CommunityBookStatus.SUBMITTED)
        original = list(cb_views.COMMUNITY_BOOK_ADMIN_IDS)
        cb_views.COMMUNITY_BOOK_ADMIN_IDS[:] = [self.admin_user.id]
        self.addCleanup(lambda: cb_views.COMMUNITY_BOOK_ADMIN_IDS.__setitem__(slice(None), original))

        self.client.force_login(self.admin_user)
        response = self._get_text(title)
        self.assertEqual(response.status_code, 404, response.content)

    def test_anyone_gets_200_from_text_api_once_approved(self):
        title = self._make_book(self.user, status=CommunityBookStatus.APPROVED)
        self.client.force_login(self.other_user)
        response = self._get_text(title)
        self.assertEqual(response.status_code, 200, response.content)

    def test_third_party_gets_404_from_text_api_on_rejected_book(self):
        title = self._make_book(self.user, status=CommunityBookStatus.REJECTED)
        self.client.force_login(self.other_user)
        response = self._get_text(title)
        self.assertEqual(response.status_code, 404)

    # --- Cached API path (index_api GET / /api/v2/index): same all-or-nothing rule ---

    def test_index_api_404s_for_non_approved_book_even_for_submitter(self):
        title = self._make_book(self.user, status=CommunityBookStatus.SUBMITTED, with_version=False)
        self.client.force_login(self.user)
        response = self._get_index(title)
        self.assertEqual(response.status_code, 404, response.content)

    def test_index_api_404s_for_non_approved_book_for_anonymous(self):
        title = self._make_book(self.user, status=CommunityBookStatus.SUBMITTED, with_version=False)
        response = self._get_index(title)
        self.assertEqual(response.status_code, 404, response.content)

    def test_index_api_200s_once_approved(self):
        title = self._make_book(self.user, status=CommunityBookStatus.APPROVED, with_version=False)
        response = self._get_index(title)
        self.assertEqual(response.status_code, 200, response.content)

    # --- Uncached HTML reader path (catchall): per-user access is safe here ---
    #
    # These do NOT go through self.client / the full view stack, because
    # doing so for an *allowed* request would render the full text_panels
    # template, which requires a webpack build (node/webpack-stats.client.json)
    # that does not exist in this environment -- and full-page rendering is
    # not something an authorization-gate test should depend on regardless.
    # Denied cases instead call catchall() directly via RequestFactory and
    # assert Http404 IS raised, before any rendering is reached. Allowed
    # cases assert two things separately, without ever rendering: (1) the
    # gate's decision, via can_view_community_book() directly, and (2) that
    # catchall() consults that decision and does not raise Http404 for that
    # same user, with text_panels() mocked out purely so the test never
    # touches webpack.

    def test_third_party_gets_404_from_html_reader_on_submitted_book(self):
        title = self._make_book(self.user, status=CommunityBookStatus.SUBMITTED)
        request, tref = self._catchall_request(title, self.other_user)
        with self.assertRaises(Http404):
            reader_views.catchall(request, tref)

    def test_submitter_is_not_gated_out_of_html_reader_on_own_submitted_book(self):
        title = self._make_book(self.user, status=CommunityBookStatus.SUBMITTED)
        idx = Index().load({"title": title})
        self.assertTrue(can_view_community_book(idx, self.user))

        request, tref = self._catchall_request(title, self.user)
        with mock.patch.object(reader_views, "text_panels", return_value=HttpResponse("ok")) as mocked_text_panels:
            reader_views.catchall(request, tref)  # must not raise Http404
        mocked_text_panels.assert_called_once()

    def test_admin_is_not_gated_out_of_html_reader_on_submitted_book(self):
        title = self._make_book(self.other_user, status=CommunityBookStatus.SUBMITTED)
        original = list(cb_views.COMMUNITY_BOOK_ADMIN_IDS)
        cb_views.COMMUNITY_BOOK_ADMIN_IDS[:] = [self.admin_user.id]
        self.addCleanup(lambda: cb_views.COMMUNITY_BOOK_ADMIN_IDS.__setitem__(slice(None), original))

        idx = Index().load({"title": title})
        self.assertTrue(can_view_community_book(idx, self.admin_user))

        request, tref = self._catchall_request(title, self.admin_user)
        with mock.patch.object(reader_views, "text_panels", return_value=HttpResponse("ok")) as mocked_text_panels:
            reader_views.catchall(request, tref)  # must not raise Http404
        mocked_text_panels.assert_called_once()

    def test_third_party_is_not_gated_out_of_html_reader_once_approved(self):
        title = self._make_book(self.user, status=CommunityBookStatus.APPROVED)
        idx = Index().load({"title": title})
        self.assertTrue(can_view_community_book(idx, self.other_user))

        request, tref = self._catchall_request(title, self.other_user)
        with mock.patch.object(reader_views, "text_panels", return_value=HttpResponse("ok")) as mocked_text_panels:
            reader_views.catchall(request, tref)  # must not raise Http404
        mocked_text_panels.assert_called_once()

    def test_third_party_gets_404_from_html_reader_on_rejected_book(self):
        title = self._make_book(self.user, status=CommunityBookStatus.REJECTED)
        request, tref = self._catchall_request(title, self.other_user)
        with self.assertRaises(Http404):
            reader_views.catchall(request, tref)


class _FakeCommunityBookIndex:
    def __init__(self, title, status):
        self.title = title
        self.communityBook = {"status": status} if status is not None else None

    @property
    def is_community_book(self):
        return self.communityBook is not None

    def best_time_period(self):
        class _TP:
            start = 0
        return _TP()


class _FakeCommunityBookVersion:
    def __init__(self, title, vt, lang, status):
        self.title = title
        self.versionTitle = vt
        self.language = lang
        self._index = _FakeCommunityBookIndex(title, status)

    def get_index(self):
        return self._index


class SearchIndexingExclusionTests(TestCase):
    """
    Exercises TextIndexer.index_all()'s decision of whether to index a given
    index/version, using fake Index/Version objects in place of real
    Elasticsearch and Mongo I/O (matching the pattern already used in
    sefaria/tests/search_test.py). This does NOT exercise real Elasticsearch
    indexing -- it verifies the decision predicate that gates entry into the
    per-version indexing call.
    """

    def test_non_approved_community_book_excluded_approved_included(self):
        submitted_v = _FakeCommunityBookVersion("Submitted Book", "v1", "en", CommunityBookStatus.SUBMITTED)
        rejected_v = _FakeCommunityBookVersion("Rejected Book", "v1", "en", CommunityBookStatus.REJECTED)
        approved_v = _FakeCommunityBookVersion("Approved Book", "v1", "en", CommunityBookStatus.APPROVED)
        non_community_v = _FakeCommunityBookVersion("Regular Book", "v1", "en", None)
        all_versions = [submitted_v, rejected_v, approved_v, non_community_v]

        TextIndexer._failed_versions = []
        TextIndexer._skipped_versions = []
        TextIndexer._bulk_actions = []

        indexed_titles = []

        def fake_index_version(cls, version, tries=0, action=None):
            indexed_titles.append(version.title)

        with mock.patch.object(TextIndexer, "create_version_priority_map", classmethod(lambda cls: None)), \
             mock.patch.object(TextIndexer, "create_terms_dict", classmethod(lambda cls: None)), \
             mock.patch.object(TextIndexer, "get_all_versions", classmethod(lambda cls: list(all_versions))), \
             mock.patch.object(TextIndexer, "excluded_from_search", classmethod(lambda cls, v: False)), \
             mock.patch.object(TextIndexer, "index_version", classmethod(fake_index_version)), \
             mock.patch("sefaria.search.Ref.clear_cache", lambda: None), \
             mock.patch.object(TextIndexer, "_flush_bulk_actions", classmethod(lambda cls, versions: 0)):
            TextIndexer.version_priority_map = {
                (v.title, v.versionTitle, v.language): (i, None)
                for i, v in enumerate(all_versions)
            }
            TextIndexer.index_all(index_name="text-b", debug=False, for_es=True)

        self.assertNotIn("Submitted Book", indexed_titles)
        self.assertNotIn("Rejected Book", indexed_titles)
        self.assertIn("Approved Book", indexed_titles)
        self.assertIn("Regular Book", indexed_titles)

        skipped_reasons = {s["title"]: s.get("reason") for s in TextIndexer._skipped_versions}
        self.assertEqual(skipped_reasons.get("Submitted Book"), "community_book_not_approved")
        self.assertEqual(skipped_reasons.get("Rejected Book"), "community_book_not_approved")


class LibraryCacheRegistrationTests(CommunityBooksApiTestBase):
    """
    Guards against a newly created community book being saved with
    override_dependencies=True, which skips the observers that register the
    title in the core library cache and create its VersionState. When that
    happens, Index.save() succeeds and the document exists in Mongo, but
    Ref(title) raises InputError because the running process's in-memory
    title cache never learned about the new book -- the book becomes
    unreachable even though it was "successfully" submitted.
    """

    def test_confirmed_book_is_ref_resolvable_and_has_version_state(self):
        self._mocked_gcs()
        self._mocked_parser()
        self.client.force_login(self.user)

        upload_kwargs = _upload_kwargs()
        upload_resp = self.client.post("/api/community-books/upload", data=upload_kwargs)
        self.assertEqual(upload_resp.status_code, 200, upload_resp.content)
        token = json.loads(upload_resp.content)["upload_token"]

        from django.core import signing
        title = signing.loads(token, salt="community-book-upload")["title_en"]
        self._track(title)

        confirm_resp = self.client.post(
            "/api/community-books/confirm", data=json.dumps({"upload_token": token}), content_type="application/json",
        )
        self.assertEqual(confirm_resp.status_code, 201, confirm_resp.content)

        try:
            ref = Ref(f"{title} 1")
        except Exception as e:
            self.fail(f"Ref({title!r} 1) should resolve for a just-confirmed community book, raised: {e}")
        self.assertEqual(ref.index.title, title)

        vs = VersionState(title)
        self.assertFalse(vs.is_new_state, "VersionState should have been created on Index save")
