"""
Tests for password reset URL patterns.

Ensures the password_reset_confirm URL pattern accepts tokens generated by
all supported Django versions, including Django 6's SHA-256-based tokens
which produce longer hash segments than the older SHA-1 format.
"""
import pytest
from django.urls import reverse, resolve


DJANGO6_TOKEN = "cbbab4-e586b88a5c84910507df7a562596bf"
LEGACY_SHORT_TOKEN = "abc123-def45678901234567890"
INTERNAL_RESET_TOKEN = "set-password"
SAMPLE_UIDB64 = "MYR4Nzw"


class TestPasswordResetConfirmURL:
    """Verify password_reset_confirm URL handles all Django token formats."""

    def test_reverse_with_django6_sha256_token(self):
        """Django 6 SHA-256 tokens have 32+ char hash segments."""
        url = reverse("password_reset_confirm", kwargs={
            "uidb64": SAMPLE_UIDB64,
            "token": DJANGO6_TOKEN,
        })
        assert SAMPLE_UIDB64 in url
        assert DJANGO6_TOKEN in url

    def test_reverse_with_legacy_short_token(self):
        url = reverse("password_reset_confirm", kwargs={
            "uidb64": SAMPLE_UIDB64,
            "token": LEGACY_SHORT_TOKEN,
        })
        assert LEGACY_SHORT_TOKEN in url

    def test_reverse_with_internal_set_password_token(self):
        """Django uses 'set-password' as an internal redirect token mid-flow."""
        url = reverse("password_reset_confirm", kwargs={
            "uidb64": SAMPLE_UIDB64,
            "token": INTERNAL_RESET_TOKEN,
        })
        assert INTERNAL_RESET_TOKEN in url

    def test_resolve_django6_token_url(self):
        """URL with a long token should resolve to the correct view."""
        match = resolve(f"/password/reset/confirm/{SAMPLE_UIDB64}/{DJANGO6_TOKEN}/")
        assert match.url_name == "password_reset_confirm"
        assert match.kwargs["uidb64"] == SAMPLE_UIDB64
        assert match.kwargs["token"] == DJANGO6_TOKEN

    @pytest.mark.parametrize("hash_length", [20, 32, 40, 64])
    def test_reverse_with_variable_hash_lengths(self, hash_length):
        """Token regex must not cap hash length — future algorithms may vary."""
        token = f"abc123-{'a' * hash_length}"
        url = reverse("password_reset_confirm", kwargs={
            "uidb64": SAMPLE_UIDB64,
            "token": token,
        })
        assert token in url
