apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: rollout-ready-{{ .Values.deployEnv }}
  labels:
    deployEnv: "{{ .Values.deployEnv }}"
spec:
  args:
    - name: healthcheck-hostname
  metrics:
    - name: healthcheck-ready
      provider:
        job:
          spec:
            backoffLimit: 1
            template:
              spec:
                containers:
                  - name: primer
                    image: "{{ .Values.web.containerImage.imageRegistry }}:{{ .Values.web.containerImage.tag }}"
                    command: [ "/app/build/startup/waitForRollout.bash" ]
                    env:
                      - name: TARGET_HOSTNAME
                        value: "{{`{{args.healthcheck-hostname}}`}}" # {{`...`}}
                      - name: TIMEOUT
                        value: "900"
                restartPolicy: Never
