apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: rollout-complete-{{ .Values.deployEnv }}
  labels:
    deployEnv: "{{ .Values.deployEnv }}"
spec:
  args:
    - name: revision
    - name: deployment
    - name: version
    - name: chartVersion
  metrics:
    - name: healthcheck-ready
      provider:
        job:
          spec:
            backoffLimit: 1
            template:
              spec:
                containers:
                  - name: completion-message
                    image: curlimages/curl
                    command: [ "sh"]
                    args:
                      - -c
                      - > 
                        curl
                        -X
                        POST
                        --data-urlencode
                        'payload={"channel": "#'$CHANNEL'", "username": "Deployment Status", "text": "'$ENV' revision '$REVISION' has deployed version '$VERSION' using chart '$CHART_VERSION'", "icon_emoji": ":globe_with_meridians:"}'
                        $SLACK_URL 
                        ||
                        /bin/true
                    env:
                      - name: REVISION
                        value: "{{`{{args.revision}}`}}" # {{`...`}}
                      - name: ENV   
                        value: "{{`{{args.deployment}}`}}" # {{`...`}}
                      - name: VERSION
                        value: "{{`{{args.version}}`}}" # {{`...`}}
                      - name: CHART_VERSION
                        value: "{{`{{args.chartVersion}}`}}"
                      - name: SLACK_URL
                        valueFrom:
                          secretKeyRef:
                            name: {{ template "sefaria.secrets.slackWebhook" . }}
                            key: slack-webhook
                      - name: CHANNEL
                        valueFrom:
                          secretKeyRef:
                            name: {{ template "sefaria.secrets.slackWebhook" . }}
                            key: channel
                restartPolicy: Never
