apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: rollout-priming-{{ .Values.deployEnv }}
  labels:
    deployEnv: "{{ .Values.deployEnv }}"
spec:
  args:
    - name: healthcheck-hostname
  metrics:
    - name: healthcheck-priming
      provider:
        job:
          spec:
            ttlSecondsAfterFinished: 3600
            backoffLimit: 1
            template:
              spec:
                containers:
                  - name: primer
                    image: "{{ .Values.web.containerImage.imageRegistry }}:{{ .Values.web.containerImage.tag }}"
                    command: [ "/app/build/startup/primeAll.bash" ]
                    env:
                      - name: TARGET_HOSTNAME
                        value: "{{`{{args.healthcheck-hostname}}`}}" # {{`...`}}
                restartPolicy: Never
