# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-12-05 21:25
from __future__ import unicode_literals

from django.db import migrations, models
import fields.encrypted


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('secret', fields.encrypted.EncryptedCharField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
