# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-12-31 12:16
from __future__ import unicode_literals

from django.db import migrations
import fields.file_fields


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='image',
            field=fields.file_fields.GCSImageField(blank=True, null=True, upload_to=''),
        ),
    ]
