# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-01-21 00:00
from __future__ import unicode_literals

from django.db import migrations
from django.core.management import call_command
import os


def load_initial_data(apps, schema_editor):
    """Load initial guide data from guides_data.json"""
    # Get the path to the fixture file
    fixture_file = os.path.join(os.path.dirname(
        os.path.dirname(__file__)), 'fixtures', 'guides_data.json')
    
    # Use Django's loaddata command to load the fixture
    call_command('loaddata', fixture_file)


def reverse_load_initial_data(apps, schema_editor):
    """Remove the initial guide data"""
    Guide = apps.get_model('guides', 'Guide')
    InfoCard = apps.get_model('guides', 'InfoCard')

    # Delete all InfoCard objects first (due to foreign key constraint)
    InfoCard.objects.all().delete()

    # Delete all Guide objects
    Guide.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            load_initial_data,
            reverse_load_initial_data,
        ),
    ]
