# Generated by Django 6.0.4 on 2026-07-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0002_load_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='key',
            field=models.CharField(choices=[('editor', 'editor')], help_text="Unique identifier for the guide (e.g., 'editor', 'topics')", max_length=100, unique=True, verbose_name='Guide Key'),
        ),
        migrations.AlterField(
            model_name='infocard',
            name='text_en',
            field=models.TextField(help_text='Text supports markdown.', verbose_name='Text (EN)'),
        ),
        migrations.AlterField(
            model_name='infocard',
            name='text_he',
            field=models.TextField(help_text='Text supports markdown.', verbose_name='Text (HE)'),
        ),
    ]
