# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-05-26 15:41
from __future__ import unicode_literals

from django.db import migrations


def create_default_guide_and_link_infocards(apps, schema_editor):
    """Create a default 'sheets' guide and link all existing InfoCards to it"""
    Guide = apps.get_model('guides', 'Guide')
    InfoCard = apps.get_model('guides', 'InfoCard')
    
    # Create default guide
    default_guide, created = Guide.objects.get_or_create(
        key='sheets',
        defaults={
            'title_prefix_en': 'Quick Start:',
            'title_prefix_he': 'התחלה מהירה:',
            'footer_links_json': '[]'
        }
    )
    
    # Link all existing InfoCards to the default guide
    InfoCard.objects.filter(guide__isnull=True).update(guide=default_guide)


def reverse_migration(apps, schema_editor):
    """Reverse the migration by removing the default guide"""
    Guide = apps.get_model('guides', 'Guide')
    Guide.objects.filter(key='sheets').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0002_auto_20250526_1241'),
    ]

    operations = [
        migrations.RunPython(create_default_guide_and_link_infocards, reverse_migration),
    ]
