# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-05-26 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0003_auto_20250526_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infocard',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_cards', to='guides.Guide', verbose_name='Guide'),
        ),
    ]
