# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-05-26 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0004_auto_20250526_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infocard',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
