# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-05-27 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0005_auto_20250526_1246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infocard',
            options={'ordering': ['order'], 'verbose_name': 'Info Card', 'verbose_name_plural': 'Info Cards'},
        ),
        migrations.RemoveField(
            model_name='guide',
            name='footer_links_json',
        ),
        migrations.AddField(
            model_name='guide',
            name='footer_link_1_text_en',
            field=models.CharField(blank=True, help_text='Text for the first footer link in English (optional)', max_length=255, verbose_name='Footer Link 1 Text (EN)'),
        ),
        migrations.AddField(
            model_name='guide',
            name='footer_link_1_text_he',
            field=models.CharField(blank=True, help_text='Text for the first footer link in Hebrew (optional)', max_length=255, verbose_name='Footer Link 1 Text (HE)'),
        ),
        migrations.AddField(
            model_name='guide',
            name='footer_link_1_url',
            field=models.URLField(blank=True, help_text='URL for the first footer link (optional)', verbose_name='Footer Link 1 URL'),
        ),
        migrations.AddField(
            model_name='guide',
            name='footer_link_2_text_en',
            field=models.CharField(blank=True, help_text='Text for the second footer link in English (optional)', max_length=255, verbose_name='Footer Link 2 Text (EN)'),
        ),
        migrations.AddField(
            model_name='guide',
            name='footer_link_2_text_he',
            field=models.CharField(blank=True, help_text='Text for the second footer link in Hebrew (optional)', max_length=255, verbose_name='Footer Link 2 Text (HE)'),
        ),
        migrations.AddField(
            model_name='guide',
            name='footer_link_2_url',
            field=models.URLField(blank=True, help_text='URL for the second footer link (optional)', verbose_name='Footer Link 2 URL'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='key',
            field=models.CharField(help_text="Unique identifier for the guide (e.g., 'sheets', 'topics')", max_length=100, unique=True, verbose_name='Guide Key'),
        ),
    ]
