# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-05-27 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0006_auto_20250527_0437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infocard',
            name='image_alt_en',
        ),
        migrations.RemoveField(
            model_name='infocard',
            name='image_alt_he',
        ),
        migrations.RemoveField(
            model_name='infocard',
            name='image_en',
        ),
        migrations.RemoveField(
            model_name='infocard',
            name='image_he',
        ),
        migrations.AddField(
            model_name='infocard',
            name='video_alt_en',
            field=models.CharField(blank=True, help_text='Alternative text for the video in English', max_length=255, verbose_name='Video Alt Text (EN)'),
        ),
        migrations.AddField(
            model_name='infocard',
            name='video_alt_he',
            field=models.CharField(blank=True, help_text='Alternative text for the video in Hebrew', max_length=255, verbose_name='Video Alt Text (HE)'),
        ),
        migrations.AddField(
            model_name='infocard',
            name='video_en',
            field=models.URLField(blank=True, help_text="Upload the video via Google Cloud to the Bucket 'guides-resources'and provide the URL here.", verbose_name='Video URL (EN)'),
        ),
        migrations.AddField(
            model_name='infocard',
            name='video_he',
            field=models.URLField(blank=True, help_text="Upload the video via Google Cloud to the Bucket 'guides-resources' and provide the URL here.", verbose_name='Video URL (HE)'),
        ),
    ]
