# Generated by Django 6.0.4 on 2026-06-24 09:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateTimeField(blank=True, help_text='Date the form was submitted (absent for in-the-wild / manual records).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submission_source', models.CharField(choices=[('formstack', 'Formstack'), ('in_the_wild', 'In the wild'), ('manual', 'Manual')], help_text='How this record entered the system.', max_length=20)),
                ('creator', models.CharField(blank=True, help_text='Creator name (first + last).', max_length=255)),
                ('creator_email', models.EmailField(blank=True, help_text='Creator email.', max_length=254)),
                ('submitter', models.CharField(blank=True, help_text='Submitter name / staff.', max_length=255)),
                ('salesforce_id', models.CharField(blank=True, help_text='Soft FK to a Salesforce record. Nullable, no hard dependency.', max_length=255, null=True)),
                ('is_developer', models.BooleanField(default=False, help_text='"I am a software developer professionally."')),
                ('job_title', models.CharField(blank=True, help_text='Current role / job title.', max_length=255)),
                ('found_sefaria', models.TextField(blank=True, help_text="How they heard about Sefaria's data and tools.")),
                ('sefaria_tools_used', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text="Sefaria data, endpoints, or tools used (self-reported, includes free-text 'other').")),
                ('tech_used_raw', models.TextField(blank=True, help_text='Their self-description of the tech used.')),
                ('technical_experience', models.CharField(blank=True, choices=[('None', 'None'), ('<5 years', '<5 years'), ('5-10 years', '5-10 years'), ('10+ years', '10+ years')], help_text='Years of programming experience.', max_length=20)),
                ('vibe_coded', models.BooleanField(default=False, help_text='Was this project vibe-coded?')),
                ('project_why', models.TextField(blank=True, help_text='What inspired them to build it.')),
                ('project_name', models.CharField(help_text='Project name.', max_length=255)),
                ('project_link', models.URLField(help_text='Live project URL.')),
                ('project_source_code', models.URLField(blank=True, help_text='Source code URL.', null=True)),
                ('project_reach', models.CharField(blank=True, help_text='Number of users (dropdown).', max_length=255)),
                ('project_desc', models.TextField(blank=True, help_text='Project description.')),
                ('project_category', models.CharField(blank=True, help_text='Category / categories.', max_length=255)),
                ('image_url', models.URLField(blank=True, help_text='Screenshot or thumbnail for the gallery card. Null until added.', null=True)),
                ('has_pbs_logo', models.BooleanField(default=False, help_text='Project displays the "Powered by Sefaria" logo.')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text='Staff-assigned tags (e.g. MCP, AI, Chatbot, Kabbalah).')),
                ('status', models.CharField(choices=[('live', 'Live'), ('dead', 'Dead'), ('unknown', 'Unknown')], default='unknown', help_text='Link liveness, set by the liveness job.', max_length=10)),
                ('is_buggy', models.BooleanField(default=False, help_text='Admin tag for whether the project is buggy.')),
                ('last_checked', models.DateTimeField(blank=True, help_text='When project_link was last verified by the liveness job.', null=True)),
                ('consent_to_display', models.BooleanField(default=False, help_text='Submitter consented to public display.')),
                ('is_published', models.BooleanField(default=False, help_text='Editorial publish gate, controls visibility on the public site.')),
                ('featured', models.BooleanField(default=False, help_text='Pinned / featured position in the gallery.')),
                ('notes', models.TextField(blank=True, help_text='Staff notes, anything else.', null=True)),
            ],
            options={
                'verbose_name': 'Powered by Sefaria Project',
                'verbose_name_plural': 'Powered by Sefaria Projects',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_published'], name='powered_by__is_publ_527563_idx'), models.Index(fields=['featured'], name='powered_by__feature_4dc9df_idx'), models.Index(fields=['status'], name='powered_by__status_a478e4_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('submission_source__in', ['formstack', 'in_the_wild', 'manual'])), name='powered_by_project_submission_source_valid'), models.CheckConstraint(condition=models.Q(('technical_experience__in', ['None', '<5 years', '5-10 years', '10+ years']), ('technical_experience', ''), _connector='OR'), name='powered_by_project_technical_experience_valid'), models.CheckConstraint(condition=models.Q(('status__in', ['live', 'dead', 'unknown'])), name='powered_by_project_status_valid')],
            },
        ),
    ]
