# Generated by Django 6.0.4 on 2026-10-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powered_by', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Editorial publish gate, controls visibility on the public site.'),
        ),
    ]
