# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-02-01 14:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    def _ensure_user_pk(apps, schema_editor):
        connection = schema_editor.connection
        if connection.vendor != "postgresql":
            return

        try:
            app_label, model_name = settings.AUTH_USER_MODEL.split(".")
        except ValueError:
            return

        try:
            user_model = apps.get_model(app_label, model_name)
        except LookupError:
            return

        table = user_model._meta.db_table
        pk_column = user_model._meta.pk.column

        with connection.cursor() as cursor:
            if table not in connection.introspection.table_names(cursor):
                return

            cursor.execute(
                "SELECT 1 FROM pg_constraint WHERE contype = 'p' AND conrelid = %s::regclass",
                [table],
            )
            if cursor.fetchone():
                return

            constraint_name = "%s_pkey" % table
            qn = connection.ops.quote_name
            cursor.execute(
                "ALTER TABLE %s ADD CONSTRAINT %s PRIMARY KEY (%s)"
                % (qn(table), qn(constraint_name), qn(pk_column))
            )

    operations = [
        migrations.RunPython(_ensure_user_pk, reverse_code=migrations.RunPython.noop),
        migrations.CreateModel(
            name='UserExperimentSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiments', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='experiment_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User experiment settings',
                'verbose_name_plural': 'User experiment settings',
            },
        ),
    ]
