# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-02-25 07:29
from __future__ import unicode_literals

from django.db import migrations, models


def create_default_welcome(apps, schema_editor):
    ChatbotWelcomeMessage = apps.get_model("reader", "ChatbotWelcomeMessage")
    ChatbotWelcomeMessage.objects.get_or_create(
        key="default",
        defaults={"welcome": "", "restart": ""},
    )


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotWelcomeMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='default', help_text="Identifier for this message set (e.g. 'default')", max_length=50, unique=True)),
                ('welcome', models.TextField(default='', help_text='Message shown when chat is empty (i.e. first-time)')),
                ('restart', models.TextField(default='', help_text='Message shown on restart button')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chatbot welcome message',
                'verbose_name_plural': 'Chatbot welcome messages',
                'ordering': ['key'],
            },
        ),
        migrations.RunPython(create_default_welcome, migrations.RunPython.noop),
    ]
