# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-03-05 11:34
from __future__ import unicode_literals

from django.db import migrations, models


def create_default_welcome(apps, schema_editor):
    """Create default welcome message for fresh installs."""
    ChatbotWelcomeMessage = apps.get_model("chatbot", "ChatbotWelcomeMessage")
    ChatbotWelcomeMessage.objects.get_or_create(
        key="default",
        defaults={
            "welcome_english": "Welcome! Ask me anything about Jewish texts.",
            "welcome_hebrew": "ברוך הבא! שאל אותי כל מה שתרצה על טקסטים יהודיים.",
            "restart_english": "Start a conversation",
            "restart_hebrew": "התחל שיחה",
        },
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='ChatbotWelcomeMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='default', help_text="Identifier for this message set (e.g. 'default')", max_length=50, unique=True)),
                ('welcome_english', models.TextField(default='Welcome! Ask me anything about Jewish texts.', help_text='Welcome message (English) shown when chat is empty')),
                ('welcome_hebrew', models.TextField(default='ברוך הבא! שאל אותי כל מה שתרצה על טקסטים יהודיים.', help_text='Welcome message (Hebrew) shown when chat is empty')),
                ('restart_english', models.TextField(default='Start a conversation', help_text='Restart message (English) shown when chat is empty after restart')),
                ('restart_hebrew', models.TextField(default='התחל שיחה', help_text='Restart message (Hebrew) shown when chat is empty after restart')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chatbot welcome message',
                'verbose_name_plural': 'Chatbot welcome messages',
                'ordering': ['key'],
            },
        ),
        migrations.RunPython(create_default_welcome, migrations.RunPython.noop),
    ]
