# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-03-08 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotwelcomemessage',
            name='new_session_english',
            field=models.TextField(default='Start a new conversation', help_text='New session message (English) shown when returning user has empty chat'),
        ),
        migrations.AddField(
            model_name='chatbotwelcomemessage',
            name='new_session_hebrew',
            field=models.TextField(default='התחל שיחה חדשה', help_text='New session message (Hebrew) shown when returning user has empty chat'),
        ),
    ]
