# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-04-10 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('title_en', models.CharField(max_length=255, verbose_name='Title (EN)')),
                ('body_en', models.TextField(verbose_name='Body (EN)')),
                ('image_en', models.URLField(help_text='Upload the image via Google Cloud and provide the URL here.', verbose_name='Image URL (EN)')),
                ('title_he', models.CharField(max_length=255, verbose_name='Title (HE)')),
                ('body_he', models.TextField(verbose_name='Body (HE)')),
                ('image_he', models.URLField(help_text='Upload the image via Google Cloud and provide the URL here.', verbose_name='Image URL (HE)')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
    ]
