# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-05-26 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sourcesheets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Unique identifier for the guide (e.g., 'sheets', 'test_heb')", max_length=100, unique=True, verbose_name='Guide Key')),
                ('title_prefix_en', models.CharField(help_text="Prefix shown before tips (e.g., 'Quick Start:')", max_length=255, verbose_name='Title Prefix (EN)')),
                ('title_prefix_he', models.CharField(help_text='Prefix shown before tips in Hebrew', max_length=255, verbose_name='Title Prefix (HE)')),
                ('footer_links_json', models.TextField(default='[]', help_text="JSON array of footer links with structure: [{'text': {'en': 'Link Text', 'he': 'טקסט קישור'}, 'url': '/path'}]", verbose_name='Footer Links')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Guide',
                'verbose_name_plural': 'Guides',
                'ordering': ['key'],
            },
        ),
        migrations.AlterModelOptions(
            name='infocard',
            options={'ordering': ['guide', 'order'], 'verbose_name': 'Info Card', 'verbose_name_plural': 'Info Cards'},
        ),
        migrations.RemoveField(
            model_name='infocard',
            name='body_en',
        ),
        migrations.RemoveField(
            model_name='infocard',
            name='body_he',
        ),
        migrations.AddField(
            model_name='infocard',
            name='image_alt_en',
            field=models.CharField(blank=True, help_text='Alternative text for the image in English', max_length=255, verbose_name='Image Alt Text (EN)'),
        ),
        migrations.AddField(
            model_name='infocard',
            name='image_alt_he',
            field=models.CharField(blank=True, help_text='Alternative text for the image in Hebrew', max_length=255, verbose_name='Image Alt Text (HE)'),
        ),
        migrations.AddField(
            model_name='infocard',
            name='text_en',
            field=models.TextField(default='default text', verbose_name='Text (EN)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infocard',
            name='text_he',
            field=models.TextField(default='default text', verbose_name='Text (HE)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='infocard',
            name='image_en',
            field=models.URLField(blank=True, help_text='Upload the image via Google Cloud and provide the URL here.', verbose_name='Image URL (EN)'),
        ),
        migrations.AlterField(
            model_name='infocard',
            name='image_he',
            field=models.URLField(blank=True, help_text='Upload the image via Google Cloud and provide the URL here.', verbose_name='Image URL (HE)'),
        ),
        migrations.AddField(
            model_name='infocard',
            name='guide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='info_cards', to='sourcesheets.Guide', verbose_name='Guide'),
        ),
    ]
