apiVersion: v1
kind: ConfigMap
metadata:
  name: robots-txt-{{ .Values.deployEnv }}
  labels:
    deployEnv: {{ .Values.deployEnv | quote }}
    {{- include "sefaria.labels" . | nindent 4 }}
data:
  robots.txt: |-
    User-agent: *
{{- if eq .Values.sandbox "true" }}
    Disallow: /
{{- else }}
    Disallow: /activity/
    Disallow: /login?next=*
    Disallow: /register?next=*
{{- end }}
