{{- if and .Values.cronJobs.rambiWebpagesWeekly.enabled .Values.gpuServer }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.deployEnv }}-rambi-update
  labels:
    {{- include "sefaria.labels" . | nindent 4 }}
spec:
  schedule: "0 0 * * 6"
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          containers:
          - name: rambi-update
            image: "{{ .Values.linker.containerImage.imageRegistry }}:{{ .Values.linker.containerImage.tag }}"
            env:
            - name: REDIS_HOST
              value: "redis-{{ .Values.deployEnv }}"
            - name: NODEJS_HOST
              value: "node-{{ .Values.deployEnv }}-{{ .Release.Revision }}"
            - name: VARNISH_HOST
              value: "varnish-{{ .Values.deployEnv }}-{{ .Release.Revision }}"
            - name: ENABLE_LINKER
              value: "True"
            - name: DISABLE_AUTOCOMPLETER
              value: "True"
            - name: GPU_SERVER
              value: {{ .Values.gpuServer }}
            envFrom:
            - secretRef:
                name: {{ .Values.secrets.localSettings.ref }}
                optional: true
            - secretRef:
                name: local-settings-secrets-{{ .Values.deployEnv }}
                optional: true
            - configMapRef:
                name: local-settings-{{ .Values.deployEnv }}
            volumeMounts:
              - mountPath: /app/sefaria/local_settings.py
                name: local-settings
                subPath: local_settings.py
                readOnly: true
            command: ["bash"]
            args: [
              "-c",
              "pip install pymarc==4.2.2 && /app/run /app/scripts/scheduled/parse_rambi_webpages.py"
            ]
          restartPolicy: Never
          volumes:
          - name: local-settings
            configMap:
              name: local-settings-file-{{ .Values.deployEnv }}
              items:
                - key: local_settings.py
                  path: local_settings.py
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
{{- end }}
