{{- if .Values.cronJobs.reindexElasticSearch.enabled }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.deployEnv }}-reindex-elastic-search
  labels:
    {{- include "sefaria.labels" . | nindent 4 }}
spec:
  schedule: "0 21 * * 5"
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          serviceAccountName: {{ .Values.deployEnv }}-reindex-orchestrator
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - mongo
                topologyKey: kubernetes.io.hostname
          containers:
          - name: reindex-elastic-search
            image: "{{ .Values.web.containerImage.imageRegistry }}:{{ .Values.web.containerImage.tag }}"
            resources:
              {{- toYaml .Values.cronJobs.reindexElasticSearch.orchestratorResources | nindent 14 }}
            env:
            - name: K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: SHARD_COUNT
              value: "{{ .Values.cronJobs.reindexElasticSearch.shardCount }}"
            - name: SHARD_JOB_IMAGE
              value: "{{ .Values.web.containerImage.imageRegistry }}:{{ .Values.web.containerImage.tag }}"
            - name: SHARD_JOB_NAME
              value: "{{ .Values.deployEnv }}-reindex-shard"
            - name: ELASTIC_ADMIN_SECRET
              value: '{{ template "sefaria.secrets.elasticAdmin" . }}'
            - name: LOCAL_SETTINGS_REF_SECRET
              value: "{{ .Values.secrets.localSettings.ref }}"
            - name: LOCAL_SETTINGS_CONFIGMAP
              value: "local-settings-{{ .Values.deployEnv }}"
            - name: LOCAL_SETTINGS_SECRET
              value: "local-settings-secrets-{{ .Values.deployEnv }}"
            - name: LOCAL_SETTINGS_FILE_CONFIGMAP
              value: "local-settings-file-{{ .Values.deployEnv }}"
            - name: SEARCH_HOST
              value: "elasticsearch-1b-es-http.elasticsearch.svc"
            - name: SEARCH_PORT
              value: "9200"
            - name: SEARCH_PATH
              value: ""
            - name: SEARCH_SSL_ENABLE
              value: "false"
            - name: REDIS_HOST
              value: "redis-{{ .Values.deployEnv }}"
            - name: NODEJS_HOST
              value: "node-{{ .Values.deployEnv }}-{{ .Release.Revision }}"
            - name: VARNISH_HOST
              value: "varnish-{{ .Values.deployEnv }}-{{ .Release.Revision }}"
            envFrom:
            - secretRef:
                name: {{ template "sefaria.secrets.elasticAdmin" . }}
            - secretRef:
                name: {{ .Values.secrets.localSettings.ref }}
                optional: true
            - configMapRef:
                name: local-settings-{{ .Values.deployEnv }}
            - secretRef:
                name: local-settings-secrets-{{ .Values.deployEnv }}
                optional: true
            volumeMounts:
              - mountPath: /app/sefaria/local_settings.py
                name: local-settings
                subPath: local_settings.py
                readOnly: true
            command: ["bash"]
            args: [
              "-c",
              "mkdir -p /log && touch /log/sefaria_book_errors.log && pip install numpy kubernetes && /app/run /app/scripts/scheduled/reindex_orchestrator.py"
            ]
          restartPolicy: Never
          volumes:
          - name: local-settings
            configMap:
              name: local-settings-file-{{ .Values.deployEnv }}
              items:
                - key: local_settings.py
                  path: local_settings.py
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
{{- end }}
