{{- if .Values.cronJobs.trello.enabled }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.deployEnv }}-trello
  labels:
    {{- include "sefaria.labels" . | nindent 4 }}
spec:
  schedule: "0 0 * * 6"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - mongo
                topologyKey: kubernetes.io.hostname
          containers:
          - name: trello
            image: "{{ .Values.web.containerImage.imageRegistry }}:{{ .Values.web.containerImage.tag }}"
            env:
              - name: REDIS_HOST
                value: "redis-{{ .Values.deployEnv }}"
              - name: NODEJS_HOST
                value: "node-{{ .Values.deployEnv }}-{{ .Release.Revision }}"
              - name: VARNISH_HOST
                value: "varnish-{{ .Values.deployEnv }}-{{ .Release.Revision }}"
              - name: SLACK_URL
                valueFrom:
                  secretKeyRef:
                    name: {{ template "sefaria.secrets.slackWebhook" . }}
                    key: slack-webhook
            envFrom:
            - secretRef:
                name: {{ .Values.secrets.localSettings.ref }}
                optional: true
            - secretRef:
                name: local-settings-secrets-{{ .Values.deployEnv }}
                optional: true
            - configMapRef:
                name: local-settings-{{ .Values.deployEnv }}
            - secretRef:
                name: trello-secret
            volumeMounts:
              - mountPath: /app/sefaria/local_settings.py
                name: local-settings
                subPath: local_settings.py
                readOnly: true
            command: ["bash"]
            args: [
              "-c",
              "/app/run /app/scripts/scheduled/webpages_cronjob.py"
            ]
            resources:
              limits:
                memory: "1.5Gi"
          restartPolicy: Never
          volumes:
          - name: local-settings
            configMap:
              name: local-settings-file-{{ .Values.deployEnv }}
              items:
                - key: local_settings.py
                  path: local_settings.py
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
{{- end }}
