name: "Build a container image"
description: "Reusable build step for web/node images"

inputs:
  app:
    required: true
  image:
    required: true
  git_ref:
    required: true
  datetime:
    required: true
  image_tag:
    required: true
  build_args:
    required: false
    default: ""
  gke_project_id:
    required: true
  gke_sa:
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.git_ref }}

    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3

    - id: auth
      uses: google-github-actions/auth@v2
      with:
        token_format: access_token
        workload_identity_provider: ${{format('projects/{0}/locations/global/workloadIdentityPools/github/providers/github', inputs.gke_project_id ) }}
        service_account: ${{ inputs.gke_sa }}

    - uses: docker/login-action@v3
      with:
        registry: us-east1-docker.pkg.dev
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}

    - id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ inputs.image }}
        tags: |
          type=raw,value=${{ inputs.image_tag }}-${{ inputs.datetime }}
          type=raw,value=${{ inputs.image_tag }}
          type=raw,value=latest
        flavor: latest=false

    - id: build
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./build/${{ inputs.app }}/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: ${{ inputs.build_args }}
