apiVersion: v1
kind: Service
metadata:
  name: nginx-{{ .Values.deployEnv }}
  labels:
    deployEnv: "{{ .Values.deployEnv }}"
    app: nginx-{{ .Values.deployEnv }}
    sandbox: "{{ .Values.sandbox }}"
    {{- if eq .Values.sandbox "true" }}
    sandbox-name: "{{ .Values.deployEnv }}"
    {{- end }}
spec:
  type: {{ if eq .Values.sandbox "true" }}ClusterIP{{ else }}NodePort{{ end }}
  ports:
  - name: http
    port: 80
  - name: https
    port: 443
  selector:
    app: nginx-{{ .Values.deployEnv }} # not strictly needed since this managed by Argo Rollout
