{{- range $index, $value := untilStep (int (sub .Release.Revision .Values.previousServicesCount)) (int (add .Release.Revision 1)) 1 }}
{{- if gt $value 0 }}
---
apiVersion: v1
kind: Service
metadata:
  name: web-{{ $.Values.deployEnv }}-{{ $value }}
  labels:
    app: web-{{ $.Values.deployEnv }}
    deployEnv: "{{ $.Values.deployEnv }}"
    stackRole: django
spec:
  ports:
  - port: 80
  selector:
    app: "web-{{ $.Values.deployEnv }}"
    releaseRevision: "{{ $value }}"
{{- end}}
{{- end}}
