#!/usr/bin/env node
/**
 * Dark-mode codemod: rewrites colour literals and raw palette var() uses in the SPA stylesheets
 * to semantic var(--color-*) tokens defined in static/css/theme-tokens.css.
 *
 *   node scripts/darkmode/tokenize-css.js            # rewrite files, regenerate legacy tokens + baseline
 *   node scripts/darkmode/tokenize-css.js --check    # exit 1 if a rewrite would change anything
 *   node scripts/darkmode/tokenize-css.js --report <file.json>   # also write the per-file report
 *
 * Guarantees:
 *  - Exact-light invariant: a colour is replaced only by a token whose light value is the same
 *    colour (resolved through color-palette.css). Anything else is an error.
 *  - Deterministic and idempotent: the output depends only on the inputs, and a second run changes
 *    nothing.
 *  - Mapping is driven by scripts/darkmode/color-map.json:
 *      skip     : selector/at-rule patterns left untouched (legacy reader themes, print, staff UI)
 *      rules    : context overrides {sel, file?, cls, color, token}, first match wins
 *      colors   : default token per colour per property class
 *      legacy   : 1:1 tokens for colours that have no exact semantic token; each has a reviewed
 *                 dark value. They are written into theme-tokens.css between the BEGIN/END markers.
 */
'use strict';
const fs = require('fs');
const path = require('path');
const P = require('./css-colors');

const REPO = path.resolve(__dirname, '..', '..');
const CSS_DIR = path.join(REPO, 'static', 'css');
const MAP_FILE = path.join(__dirname, 'color-map.json');
const TOKENS_FILE = path.join(CSS_DIR, 'theme-tokens.css');
const PALETTE_FILE = path.join(CSS_DIR, 'color-palette.css');
const BASELINE_FILE = path.join(CSS_DIR, '.color-literal-baseline.json');
const B_BLOCK_MARKER = '/* ===== ThemeToggle (darkmode chunk B) ===== */';
const LEGACY_BEGIN = '/* BEGIN legacy tokens (generated by scripts/darkmode/tokenize-css.js; do not edit) */';
const LEGACY_END = '/* END legacy tokens */';
const KEEP = '=keep'; // map value for a literal that is intentionally theme-invariant

function readMap() { return JSON.parse(fs.readFileSync(MAP_FILE, 'utf8')); }

function paletteEnv() {
  const env = {};
  for (const d of P.customPropertyDefs(fs.readFileSync(PALETTE_FILE, 'utf8'))) if (d.selector === ':root') env[d.name] = d.value;
  return env;
}

/** Light-theme token values: :root definitions of theme-tokens.css outside any @media. */
function tokenDefs(src) {
  const light = {}, dark = {};
  for (const d of P.customPropertyDefs(src)) {
    if (d.selector === ':root' && d.atRules.length === 0) light[d.name] = d.value;
    else if (d.selector === ':root[data-theme="dark"]' && d.atRules.join(' ') === '@media screen') dark[d.name] = d.value;
  }
  return { light, dark };
}

/** Rewrite the generated legacy section of theme-tokens.css from the map. */
function renderTokens(src, map) {
  const names = Object.keys(map.legacy || {}).sort();
  const parts = src.split(LEGACY_BEGIN);
  if (parts.length !== 3) throw new Error('theme-tokens.css must contain exactly two legacy BEGIN markers');
  const fill = (chunk, indent, key) => {
    const end = chunk.indexOf(LEGACY_END);
    if (end === -1) throw new Error('missing legacy END marker');
    const body = names.map(n => `${indent}${n}: ${map.legacy[n][key]};`).join('\n');
    return '\n' + (body ? body + '\n' : '') + indent + chunk.slice(end);
  };
  return parts[0] + LEGACY_BEGIN + fill(parts[1], '  ', 'light') + LEGACY_BEGIN + fill(parts[2], '    ', 'dark');
}

function compile(map) {
  return {
    skip: (map.skip || []).map(s => ({ ...s, re: s.sel ? new RegExp(s.sel) : null, atRe: s.atRule ? new RegExp(s.atRule) : null })),
    rules: (map.rules || []).map(r => ({ ...r, re: new RegExp(r.sel), colors: [].concat(r.color).map(c => c.startsWith('--') ? c : P.normColor(c)) })),
  };
}

function lookup(map, compiled, file, decl, cls, colorKey, paletteName) {
  const sel = decl.selector.replace(/\s+/g, ' ');
  for (const r of compiled.rules) {
    if (r.file && r.file !== file) continue;
    if (r.cls && [].concat(r.cls).indexOf(cls) === -1) continue;
    if (r.prop && !new RegExp(r.prop).test(decl.prop)) continue;
    if (!(r.colors.includes(colorKey) || (paletteName && r.colors.includes(paletteName)))) continue;
    if (!r.re.test(sel)) continue;
    return r.token;
  }
  const byPal = paletteName && map.palette && map.palette[paletteName];
  if (byPal && byPal[cls]) return byPal[cls];
  const byColor = map.colors[colorKey];
  if (byColor && byColor[cls]) return byColor[cls];
  return null;
}

function skipReason(compiled, file, decl, src) {
  const sel = decl.selector.replace(/\s+/g, ' ');
  for (const s of compiled.skip) {
    if (s.file && s.file !== file) continue;
    if (s.re && s.re.test(sel)) return s.reason;
    if (s.atRe && decl.atRules.some(a => s.atRe.test(a))) return s.reason;
  }
  const lineText = src.split('\n')[decl.line - 1] || '';
  if (/theme-exempt/.test(lineText)) return 'theme-exempt comment';
  return null;
}

function run({ check = false, reportFile = null } = {}) {
  const map = readMap();
  const compiled = compile(map);
  const palEnv = paletteEnv();
  const paletteNames = new Set(Object.keys(palEnv));

  // tokens: regenerate legacy section first so light values are available
  const tokSrcOld = fs.readFileSync(TOKENS_FILE, 'utf8');
  const tokSrc = renderTokens(tokSrcOld, map);
  const { light } = tokenDefs(tokSrc);
  const env = { ...palEnv, ...light };
  const tokenLight = name => {
    if (env[name] === undefined) throw new Error(`token ${name} is not defined in theme-tokens.css`);
    return P.resolveColor(env[name], env);
  };

  const changed = [];
  const report = {};
  if (tokSrc !== tokSrcOld) { changed.push('theme-tokens.css'); if (!check) fs.writeFileSync(TOKENS_FILE, tokSrc); }

  for (const file of map.targets) {
    const abs = path.join(CSS_DIR, file);
    const full = fs.readFileSync(abs, 'utf8');
    const cut = full.indexOf(B_BLOCK_MARKER);
    const src = cut === -1 ? full : full.slice(0, cut);
    const tail = cut === -1 ? '' : full.slice(cut);
    const scss = file.endsWith('.scss');
    const rep = { replaced: 0, byToken: {}, kept: [], skipped: [], unmapped: [] };
    const edits = [];
    const decls = P.findDeclarations(src, { scss });
    // Filled controls often draw a border in the same colour as their fill. Give such a border the
    // fill's token so the two stay identical in dark mode too (instead of an outline token).
    const fillTokenByBlock = {};
    for (const decl of decls) {
      if (P.propClass(decl.prop) !== 'bg' || skipReason(compiled, file, decl, src)) continue;
      const add = (key, pal) => { const t = lookup(map, compiled, file, decl, 'bg', key, pal); if (t && t !== KEEP) (fillTokenByBlock[decl.blockId] = fillTokenByBlock[decl.blockId] || {})[key] = t; };
      P.findColorsInValue(decl).forEach(c => add(P.normColor(c.text), null));
      P.findVarsInValue(decl).filter(v => paletteNames.has(v.name) && !v.inert).forEach(v => add(P.resolveColor(`var(${v.name})`, palEnv), v.name));
    }
    for (const decl of decls) {
      const cls = P.propClass(decl.prop);
      const colors = P.findColorsInValue(decl);
      const vars = P.findVarsInValue(decl).filter(v => paletteNames.has(v.name) && !v.inert);
      if (!colors.length && !vars.length) continue;
      const where = `${decl.line} ${decl.selector.replace(/\s+/g, ' ').slice(0, 90)} { ${decl.prop} }`;
      const reason = cls === null ? `unclassified property ${decl.prop}` : cls === 'def' ? 'definition (hand-edited)' : skipReason(compiled, file, decl, src);
      const items = colors.map(c => ({ ...c, key: P.normColor(c.text), pal: null }))
        .concat(vars.map(v => ({ start: v.start, end: v.end, text: v.name, key: P.resolveColor(`var(${v.name})`, palEnv), pal: v.name })));
      for (const it of items) {
        if (reason) { rep.skipped.push(`${where}: ${it.text} (${reason})`); continue; }
        const sameFill = cls === 'border' && (fillTokenByBlock[decl.blockId] || {})[it.key];
        const token = sameFill || lookup(map, compiled, file, decl, cls, it.key, it.pal);
        if (!token) { rep.unmapped.push({ line: decl.line, cls, color: it.key, text: it.text, where }); continue; }
        if (token === KEEP) { rep.kept.push(`${where}: ${it.text}`); continue; }
        const tl = tokenLight(token);
        if (tl !== it.key) throw new Error(`${file}:${decl.line} exact-light violation: ${it.text} (${it.key}) -> ${token} (${tl})`);
        const s = decl.valueStart + it.start, e = decl.valueStart + it.end;
        edits.push({ s, e, text: it.pal ? token : `var(${token})` });
        rep.replaced++; rep.byToken[token] = (rep.byToken[token] || 0) + 1;
      }
    }
    edits.sort((a, b) => b.s - a.s);
    let out = src;
    for (const ed of edits) out = out.slice(0, ed.s) + ed.text + out.slice(ed.e);
    out += tail;
    if (out !== full) { changed.push(file); if (!check) fs.writeFileSync(abs, out); }
    report[file] = rep;
  }
  if (reportFile) fs.writeFileSync(reportFile, JSON.stringify(report, null, 2) + '\n');
  return { changed, report };
}

/** Per-file literal and palette-var counts for every stylesheet (the ratchet baseline). */
function computeCounts() {
  const palEnv = paletteEnv();
  const paletteNames = new Set(Object.keys(palEnv));
  const map = readMap();
  const out = {};
  const walk = dir => fs.readdirSync(dir, { withFileTypes: true }).sort((a, b) => a.name < b.name ? -1 : 1).forEach(ent => {
    const abs = path.join(dir, ent.name);
    if (ent.isDirectory()) return walk(abs);
    if (!/\.(css|scss)$/.test(ent.name)) return;
    const rel = path.relative(CSS_DIR, abs).split(path.sep).join('/');
    if ((map.ratchetExempt || {})[rel]) return;
    // compiled .css of a .scss source is counted through its source only
    if (rel.endsWith('.css') && fs.existsSync(abs.replace(/\.css$/, '.scss'))) return;
    const r = P.countFile(fs.readFileSync(abs, 'utf8'), { scss: rel.endsWith('.scss'), paletteNames });
    if (r.literals || r.paletteVars) out[rel] = { literals: r.literals, paletteVars: r.paletteVars };
  });
  walk(CSS_DIR);
  return out;
}

/** Write static/css/.color-literal-baseline.json from the current tree. Returns true if it changed. */
function writeBaseline() {
  const baseline = JSON.stringify({
    _comment: 'Colour-literal ratchet baseline: per stylesheet, the number of colour literals and raw palette var() uses. Counts may only go down. Regenerate with `node scripts/darkmode/tokenize-css.js --baseline`. See static/js/tests/cssColorLiterals.test.js.',
    files: computeCounts(),
  }, null, 2) + '\n';
  const old = fs.existsSync(BASELINE_FILE) ? fs.readFileSync(BASELINE_FILE, 'utf8') : '';
  if (old === baseline) return false;
  fs.writeFileSync(BASELINE_FILE, baseline);
  return true;
}

if (require.main === module) {
  const args = process.argv.slice(2);
  const check = args.includes('--check');
  if (args.includes('--baseline')) { writeBaseline(); process.exit(0); }
  const ri = args.indexOf('--report');
  const reportFile = ri === -1 ? null : args[ri + 1];
  const { changed, report } = run({ check, reportFile });
  let unmapped = 0, replaced = 0;
  for (const [f, r] of Object.entries(report)) {
    unmapped += r.unmapped.length; replaced += r.replaced;
    console.log(`${f.padEnd(28)} replaced ${String(r.replaced).padStart(4)}  kept ${String(r.kept.length).padStart(3)}  skipped ${String(r.skipped.length).padStart(3)}  unmapped ${String(r.unmapped.length).padStart(3)}`);
  }
  console.log(`total replaced ${replaced}, unmapped ${unmapped}`);
  if (!check && writeBaseline()) changed.push('.color-literal-baseline.json');
  if (changed.length) console.log((check ? 'would change: ' : 'changed: ') + changed.join(', '));
  if (check && changed.length) process.exit(1);
}

module.exports = { run, computeCounts, writeBaseline, BASELINE_FILE, MAP_FILE, TOKENS_FILE, CSS_DIR, tokenDefs, paletteEnv, renderTokens, B_BLOCK_MARKER };
