{{- if eq .Values.backup.mongo.enabled true }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.deployEnv }}-mongobackup
  labels:
    {{- include "sefaria.labels" . | nindent 4 }}
spec:
  concurrencyPolicy: Replace
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          serviceAccount: {{ .Values.backup.mongo.serviceAccount }}
          affinity:
            podAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 1
                podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                    - key: app
                      operator: In
                      values:
                      - mongo
                  topologyKey: kubernetes.io/hostname
          tolerations:
            - key: schedule-on-database-vm
              operator: "Equal"
              value: "true"
              effect: "NoSchedule"
            - key: mongo-replicaset 
              operator: "Equal"
              value: "reserved"
              effect: "NoSchedule"
          initContainers:
          - name: mongo-dumper
            image:  mongo:{{ .Values.backup.mongo.version }}
            envFrom:
            - secretRef:
                name: {{ .Values.secrets.localSettings.ref }}
                optional: true
            - configMapRef:
                name: local-settings-{{ .Values.deployEnv }}
            - secretRef:
                name: local-settings-secrets-{{ .Values.deployEnv }}
                optional: true
            volumeMounts:
            - name: shared-volume
              mountPath: /mongodumps/shared_volume
            - name: create-dumps-script
              mountPath: /scripts/create-dumps.sh
              subPath: create-dumps.sh
              readOnly: true
            command: ["bash"]
            args: ["-c", "/scripts/create-dumps.sh"]
            resources:
              limits:
                memory: "500Mi"
          containers:
          - name: mongodump-uploader
            image:  google/cloud-sdk
            volumeMounts:
            - name: shared-volume
              mountPath: /mongodumps/shared_volume
            - name: upload-dumps-script
              mountPath: /scripts/upload-dumps.sh
              subPath: upload-dumps.sh
              readOnly: true
            env:
            - name: PREFIX
              value: {{ .Values.backup.mongo.prefix }}
            - name: BUCKET
              value: {{ .Values.backup.mongo.bucket }}
            - name: ARCHIVE_BUCKET
              value: {{ .Values.backup.mongo.archiveBucket }}
            - name: SLACK_URL
              valueFrom:
                secretKeyRef:
                  name: {{ template "sefaria.secrets.slackWebhook" . }}
                  key: slack-webhook
            command: ["bash"]
            args: ["-c", "/scripts/upload-dumps.sh"]
            resources:
              limits:
                memory: "500Mi"
          restartPolicy: OnFailure
          volumes:
          - name: create-dumps-script
            configMap:
              name: create-dumps-{{ .Values.deployEnv }}
              defaultMode: 0755
          - name: upload-dumps-script
            configMap:
              name: upload-dumps-{{ .Values.deployEnv }}
              defaultMode: 0755
          - name: shared-volume
            emptyDir: {}
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
{{- end }}
