{{- if .Values.backup.sitemaps.enabled }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.deployEnv }}-sitemaps
  labels:
    {{- include "sefaria.labels" . | nindent 4 }}
spec:
  schedule: "0 5 * * *"
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          volumes:
          - name: local-settings
            configMap:
              name: local-settings-file-{{ .Values.deployEnv }}
              items:
                - key: local_settings.py
                  path: local_settings.py
          - name: shared-volume
            emptyDir: {}
          serviceAccount: {{ .Values.backup.sitemaps.serviceAccount }}
          initContainers:
          - name: sitemap-generator
            image: "{{ .Values.web.containerImage.imageRegistry }}:{{ .Values.web.containerImage.tag }}"
            env:
            - name: REDIS_HOST
              value: "redis-{{ .Values.deployEnv }}"
            - name: NODEJS_HOST
              value: "node-{{ .Values.deployEnv }}-{{ .Release.Revision }}"
            - name: VARNISH_HOST
              value: "varnish-{{ .Values.deployEnv }}-{{ .Release.Revision }}"
            envFrom:
            - secretRef:
                name: {{ .Values.secrets.localSettings.ref }}
                optional: true
            - secretRef:
                name: local-settings-secrets-{{ .Values.deployEnv }}
                optional: true
            - configMapRef:
                name: local-settings-{{ .Values.deployEnv }}
            volumeMounts:
              - name: shared-volume
                mountPath: /storage
              - mountPath: /app/sefaria/local_settings.py
                name: local-settings
                subPath: local_settings.py
                readOnly: true
            command: ["bash"]
            args: ["-c", "/app/run /app/scripts/generate_sitemaps.py -o /storage/"]
          containers:
          - name: file-uploader
            image: google/cloud-sdk
            volumeMounts:
            - name: shared-volume
              mountPath: /storage
            env:
            - name: BUCKET
              value: {{ .Values.backup.sitemaps.bucket }}
            command: ["bash"]
            args: ["-c", "gsutil -m cp -r /storage/sitemaps gs://$BUCKET/static && gsutil -m acl -r ch -u AllUsers:R gs://$BUCKET/static/sitemaps/"]
          restartPolicy: Never
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 2
{{- end }}
