# https://sefaria.slack.com/archives/DNAHQ11V0/p1594892722002100
{{- if .Values.cronJobs.topicsIndexing.enabled }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.deployEnv }}-topics-indexing
  labels:
    {{- include "sefaria.labels" . | nindent 4 }}
spec:
  schedule: "0 0 * * 1"
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: topics-indexer
              image: "{{ .Values.web.containerImage.imageRegistry }}:{{ .Values.web.containerImage.tag }}"
              args: [ "yes | pip3 install numpy && touch /log/sefaria_book_errors.log && python3 /app/scripts/recalculate_secondary_topic_data.py" ]
              env:
              - name: REDIS_HOST
                value: "redis-{{ .Values.deployEnv }}"
              - name: NODEJS_HOST
                value: "node-{{ .Values.deployEnv }}-{{ .Release.Revision }}"
              - name: VARNISH_HOST
                value: "varnish-{{ .Values.deployEnv }}-{{ .Release.Revision }}"
              envFrom:
              - secretRef:
                  name: {{ .Values.secrets.localSettings.ref }}
                  optional: true
              - configMapRef:
                  name: local-settings-{{ .Values.deployEnv }}
              - secretRef:
                  name: local-settings-secrets-{{ .Values.deployEnv }}
                  optional: true
              volumeMounts:
                - mountPath: /app/sefaria/local_settings.py
                  name: local-settings
                  subPath: local_settings.py
                  readOnly: true
              resources:
                requests:
                  memory: "5Gi"
                  cpu: "1000m"
                limits:
                  memory: "8Gi"
                  cpu: "1500m"
          volumes:
          - name: local-settings
            configMap:
              name: local-settings-file-{{ .Values.deployEnv }}
              items:
                - key: local_settings.py
                  path: local_settings.py
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
{{- end }}
