#!/bin/bash

###############################################################################
# Setup Database Script
#
# Creates local_settings.py with appropriate database configuration
# Supports both SQLite (default) and PostgreSQL (with --postgres flag)
###############################################################################

set -e

# Source utility functions
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

print_success() { echo -e "${GREEN}✓ $1${NC}"; }
print_error() { echo -e "${RED}✗ ERROR: $1${NC}"; }
print_warning() { echo -e "${YELLOW}⚠ WARNING: $1${NC}"; }
print_info() { echo -e "${BLUE}ℹ $1${NC}"; }

# Backup existing local_settings.py
backup_local_settings() {
  if [ -f "sefaria/local_settings.py" ]; then
    BACKUP_FILE="sefaria/local_settings.py.backup.$(date +%Y%m%d_%H%M%S)"
    print_warning "Backing up existing local_settings.py to $BACKUP_FILE"
    cp sefaria/local_settings.py "$BACKUP_FILE"
    print_success "Backup created"
  fi
}

# Create PostgreSQL database
setup_postgresql_db() {
  print_info "Setting up PostgreSQL database..."

  # Check if PostgreSQL is running
  if ! pg_isready &> /dev/null; then
    print_error "PostgreSQL is not running"
    print_info "Starting PostgreSQL..."
    if [[ "$OS" == "macos" ]]; then
      brew services start postgresql@14
      sleep 2
    fi
  fi

  # Check if database exists
  if psql -lqt | cut -d \| -f 1 | grep -qw sefaria; then
    print_success "Database 'sefaria' already exists"
  else
    print_info "Creating database 'sefaria'..."
    createdb sefaria
    print_success "Database 'sefaria' created"
  fi
}

# Create local_settings.py
create_local_settings() {
  print_info "Creating sefaria/local_settings.py..."

  # Get absolute path to project directory
  PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

  # Get current username
  CURRENT_USER=$(whoami)

  cp sefaria/local_settings_example.py sefaria/local_settings.py
  print_success "Copied local_settings_example.py to sefaria/local_settings.py"

  cat >> sefaria/local_settings.py <<'EOF'

# --- Automated setup overrides (generated by setup.sh) ---
EOF

  if [ "$USE_POSTGRES" = true ]; then
    cat >> sefaria/local_settings.py <<'EOF'
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'sefaria',
        'USER': os.getenv('USER'),
        'PASSWORD': '',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}
EOF
    print_success "Configured for PostgreSQL"
  else
    cat >> sefaria/local_settings.py <<EOF
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': '${PROJECT_DIR}/db.sqlite',
        'USER': '',
        'PASSWORD': '',
        'HOST': '',
        'PORT': '',
    }
}
EOF
    print_success "Configured for SQLite"
  fi

  cat >> sefaria/local_settings.py <<'EOF'

# --- Local overrides appended by setup.sh ---
SILENCED_SYSTEM_CHECKS = ['captcha.recaptcha_test_key_error']

ADMINS = (
    ('Local Admin', 'admin@localhost'),
)

ADMIN_PATH = 'admin'

# Provide a deterministic but obviously non-production secret
SECRET_KEY = 'local-development-secret-key-change-in-production'

# Leave blank unless you have a service account JSON locally
GOOGLE_APPLICATION_CREDENTIALS_FILEPATH = ""

EOF

  print_success "local_settings.py created successfully"
}

# Verify database configuration
verify_database() {
  print_info "Verifying database configuration..."

  # Check if local_settings.py exists
  if [ ! -f "sefaria/local_settings.py" ]; then
    print_error "local_settings.py not found"
    exit 1
  fi

  print_success "local_settings.py exists"

  if [ "$USE_POSTGRES" = true ]; then
    # Test PostgreSQL connection
    if psql -d sefaria -c "SELECT 1;" &> /dev/null; then
      print_success "PostgreSQL connection successful"
    else
      print_error "Could not connect to PostgreSQL database"
      exit 1
    fi
  else
    # Check if SQLite path is accessible
    PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
    if [ -w "$PROJECT_DIR" ]; then
      print_success "SQLite database path is writable"
    else
      print_error "SQLite database path is not writable"
      exit 1
    fi
  fi
}

# Main function
main() {
  print_info "Setting up Django database configuration..."
  echo ""

  backup_local_settings

  if [ "$USE_POSTGRES" = true ]; then
    setup_postgresql_db
  else
    print_info "Using SQLite (no database creation needed)"
  fi

  create_local_settings
  verify_database

  echo ""
  print_success "Database configuration complete!"

  if [ "$USE_POSTGRES" = true ]; then
    print_info "Using PostgreSQL database: sefaria"
  else
    print_info "Using SQLite database: db.sqlite"
  fi
}

main
