# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-04-22 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshort', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='original_url',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='short_url',
            field=models.URLField(max_length=2000, unique=True),
        ),
    ]
