apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-{{ .Values.deployEnv }}
  labels:
    {{- include "sefaria.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: nginx-ingress
    kubernetes.io/tls-acme: "true"
  {{- if .Values.instrumentation.enabled }}
    nginx.ingress.kubernetes.io/enable-opentracing: "true"
    nginx.ingress.kubernetes.io/jaeger-service-name: {{ .Values.deployEnv }}-ingress
    nginx.ingress.kubernetes.io/jaeger-propagation-format: w3c
  {{- end }}
  {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  tls:
    {{- range $i := .Values.ingress.hosts }}
    - secretName: {{ $i.tlsRef | default ( printf "origin-%s-tls" $.Values.deployEnv ) }}
      hosts:
        - {{ tpl $i.host $ }}
        - www.{{ tpl $i.host $ }}
    {{- range $k, $v := $.Values.ingress.subdomains }}
        - {{ $k }}.{{ tpl $i.host $ }}
    {{- end }}
    {{- end }}
  rules:
    {{- range $i := .Values.ingress.hosts }}
    - host: {{ tpl $i.host $ }}
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: nginx-{{ $.Values.deployEnv }}
                port:
                  number: 80
    - host: www.{{ tpl $i.host $ }}
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: nginx-{{ $.Values.deployEnv }}
                port:
                  number: 80
    {{- range $k, $v := $.Values.ingress.subdomains }}
    - host: {{ $k }}.{{ tpl $i.host $ }}
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: nginx-{{ $.Values.deployEnv }}
                port:
                  number: 80
    {{- end }}
    {{- end }}
