apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-{{ .Values.deployEnv }}
  labels:
    {{- include "sefaria.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: nginx-ingress
  {{- if .Values.instrumentation.enabled }}
    nginx.ingress.kubernetes.io/enable-opentracing: "true"
    nginx.ingress.kubernetes.io/jaeger-service-name: {{ .Values.deployEnv }}-ingress
    nginx.ingress.kubernetes.io/jaeger-propagation-format: w3c
  {{- end }}
  {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  tls:
    - secretName: {{ template "sefaria.secrets.originTls" . }}
    {{- if or .Values.ingress.secrets.originIlTls.data .Values.ingress.secrets.originIlTls.ref }}
    - secretName: {{ template "sefaria.secrets.originIlTls" . }}
    {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ tpl .host $ | quote }}
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .serviceName | default "nginx" }}-{{ $.Values.deployEnv }}
                port:
                  number: {{ .port | default "80" }}
    {{- end }}
{{- if .Values.subdomains.sheets.enable }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-{{ .Values.deployEnv }}-sheets
  labels:
    {{- include "sefaria.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: nginx-ingress
    nginx.ingress.kubernetes.io/rewrite-target: "/sheets/$1"
  {{- if .Values.instrumentation.enabled }}
    nginx.ingress.kubernetes.io/enable-opentracing: "true"
    nginx.ingress.kubernetes.io/jaeger-service-name: {{ .Values.deployEnv }}-ingress
    nginx.ingress.kubernetes.io/jaeger-propagation-format: w3c
  {{- end }}
  {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  tls:
    - secretName: {{ .Values.deployEnv }}-tls
      hosts:
      {{- range .Values.ingress.hosts }}
        - sheets.{{ tpl .host $ }}
      {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: sheets.{{ tpl .host $ }}
      http:
        paths:
          - pathType: ImplementationSpecific
            path: /($|.*)
            backend:
              service:
                name: {{ .serviceName | default "nginx" }}-{{ $.Values.deployEnv }}
                port:
                  number: {{ .port | default "80" }}
    {{- end }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-{{ .Values.deployEnv }}-redirect
  labels:
    {{- include "sefaria.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: nginx-ingress
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/permanent-redirect: "sheets.{{ tpl ( first .Values.ingress.hosts ).host . }}$1$2"
  {{- if .Values.instrumentation.enabled }}
    nginx.ingress.kubernetes.io/enable-opentracing: "true"
    nginx.ingress.kubernetes.io/jaeger-service-name: {{ .Values.deployEnv }}-ingress
    nginx.ingress.kubernetes.io/jaeger-propagation-format: w3c
  {{- end }}
  {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  tls:
    - secretName: {{ template "sefaria.secrets.originTls" . }}
    {{- if or .Values.ingress.secrets.originIlTls.data .Values.ingress.secrets.originIlTls.ref }}
    - secretName: {{ template "sefaria.secrets.originIlTls" . }}
    {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ tpl .host $ | quote }}
      http:
        paths:
          - pathType: ImplementationSpecific
            path: /sheets(/|$)(.*)
            backend:
              service:
                name: {{ .serviceName | default "nginx" }}-{{ $.Values.deployEnv }}
                port:
                  number: {{ .port | default "80" }}
    {{- end }}
{{- end }}
