
# Giant list ordering of categories
# indentation and inclusion of duplicate categories (like "Seder Moed")
# is for readability only. The table of contents will follow this structure.
CATEGORY_ORDER = [
    "Tanakh",
        "Torah",
            "Genesis",
            "Exodus",
            "Leviticus",
            "Numbers",
            "Deuteronomy",
        "Prophets",
        "Writings",
        "Targum",
            'Onkelos Genesis',
            'Onkelos Exodus',
            'Onkelos Leviticus',
            'Onkelos Numbers',
            'Onkelos Deuteronomy',
            'Targum Jonathan on Genesis',
            'Targum Jonathan on Exodus',
            'Targum Jonathan on Leviticus',
            'Targum Jonathan on Numbers',
            'Targum Jonathan on Deuteronomy',
        'Rashi',
    "Mishnah",
        "Seder Zeraim",
        "Seder Moed",
        "Seder Nashim",
        "Seder Nezikin",
        "Seder Kodashim",
        "Seder Tahorot",
    "Talmud",
        "Bavli",
                "Seder Zeraim",
                "Seder Moed",
                "Seder Nashim",
                "Seder Nezikin",
                "Seder Kodashim",
                "Seder Tahorot",
        "Yerushalmi",
                "Seder Zeraim",
                "Seder Moed",
                "Seder Nashim",
                "Seder Nezikin",
                "Seder Kodashim",
                "Seder Tahorot",
        "Tosafot",
        "Rif",
    "Midrash",
        "Aggadic Midrash",
            "Midrash Rabbah",
        "Halachic Midrash",
    "Halakhah",
        "Mishneh Torah",
            'Introduction',
            'Sefer Madda',
            'Sefer Ahavah',
            'Sefer Zemanim',
            'Sefer Nashim',
            'Sefer Kedushah',
            'Sefer Haflaah',
            'Sefer Zeraim',
            'Sefer Avodah',
            'Sefer Korbanot',
            'Sefer Taharah',
            'Sefer Nezikim',
            'Sefer Kinyan',
            'Sefer Mishpatim',
            'Sefer Shoftim',
        'Shulchan Arukh',
        'Tur and Commentaries',  # todo: remove/rename
            'Tur',
            'Beit Yosef',
            'Darchei Moshe',
            'Bach',
            'Prisha',
            'Drisha',
        'Halakhot Gedolot',
        'Chayei Adam',
        'Chokhmat Adam',
        'Kitzur Shulchan Arukh',
        'Arukh HaShulchan',
        'Arukh HaShulchan HeAtid',
        'Ben Ish Hai',
        "Sifrei Mitzvot",
        "Issur v'Heter",
        "Monographs",
        "Other Rishonim",
        "Avodat HaKodesh (Chida)",
        "Other Achronim",
        "Peninei Halakhah",
        "Contemporary Halakhic Problems",
        "Gray Matter",
    "Kabbalah",
        "Zohar",
        "Tikkunei Zohar",
        "Zohar Chadash",
    'Liturgy',
        'Siddur',
        'Haggadah',
        'High Holidays',
        'Piyutim',
    "Jewish Thought",
        "Ancient",
        "Rishonim",
        "Maharal",
        "Acharonim",
        "Rav Kook",
        "Works of Eliezer Berkovits",
        "Modern",
    'Philosophy',   # todo: delete me after reorg
    "Tanaitic",     # todo: delete me after reorg
        "Tosefta",  # todo: move me after reorg
            "Seder Zeraim",
            "Seder Moed",
            "Seder Nashim",
            "Seder Nezikin",
            "Seder Kodashim",
            "Seder Tahorot",
        "Masechtot Ketanot",
    'Chasidut',
        "Early Works",
        "Breslov",
        "Izhbitz",
        "R' Tzadok HaKohen",
    'Musar',
    'Responsa',
        "Geonim"
        "Rashba",
        "Rambam",
        "Other Rishonim",
        "Radbaz",
        "Shoel uMeshiv",
        "Other Acharonim",
        "B'Mareh HaBazak",
        "Other Modern",
    'Apocrypha',
    'Modern Works',
    "Reference",
    'Other',
    'Tosafot',  # Commentators
    'Bartenura',
    'Rambam'
    'Yachin',
    'Boaz'
]

TOP_CATEGORIES = [
    "Tanakh",
    "Mishnah",
    "Talmud",
    "Midrash",
    "Halakhah",
    "Kabbalah",
    "Liturgy",
    "Jewish Thought",
    "Tosefta"
    "Chasidut",
    "Musar",
    "Responsa",
    "Apocrypha",
    "Reference",
]

REVERSE_ORDER = [
    'Commentary'  # Uch, STILL special casing commentary here... anything to be done??
]

