
# Giant list ordering of categories
# indentation and inclusion of duplicate categories (like "Seder Moed")
# is for readability only. The table of contents will follow this structure.
CATEGORY_ORDER = [
    "Tanakh",
        "Torah",
            "Genesis",
            "Exodus",
            "Leviticus",
            "Numbers",
            "Deuteronomy",
        "Prophets",
        "Writings",
        "Targum",
            'Onkelos Genesis',
            'Onkelos Exodus',
            'Onkelos Leviticus',
            'Onkelos Numbers',
            'Onkelos Deuteronomy',
            'Targum Jonathan on Genesis',
            'Targum Jonathan on Exodus',
            'Targum Jonathan on Leviticus',
            'Targum Jonathan on Numbers',
            'Targum Jonathan on Deuteronomy',
        "Rishonim on Tanakh",
            'Rashi',
            'Ibn Ezra',
            'Ramban',
        "Acharonim on Tanakh",
        "Modern Commentary on Tanakh",
    "Mishnah",
        "Seder Zeraim",
        "Seder Moed",
        "Seder Nashim",
        "Seder Nezikin",
        "Seder Kodashim",
        "Seder Tahorot",
        "Rishonim on Mishnah",
            'Bartenura',
        "Acharonim on Mishnah",
        "Modern Commentary on Mishnah",
    "Talmud",
        "Bavli",
                "Seder Zeraim",
                "Seder Moed",
                "Seder Nashim",
                "Seder Nezikin",
                "Seder Kodashim",
                "Seder Tahorot",
                "Minor Tractates",
        "Yerushalmi",
                "Seder Zeraim",
                "Seder Moed",
                "Seder Nashim",
                "Seder Nezikin",
                "Seder Kodashim",
                "Seder Tahorot",
        "Guides",
        "Rishonim on Talmud",
            "Tosafot",
            "Rif",
        "Acharonim on Talmud",
        "Modern Commentary on Talmud",
        "Commentary on Minor Tractates",
    "Midrash",
    "Halachic Midrash",
    "Aggadic Midrash",
            "Midrash Rabbah",
    "Halakhah",
        "Mishneh Torah",
            'Introduction',
            'Sefer Madda',
            'Sefer Ahavah',
            'Sefer Zemanim',
            'Sefer Nashim',
            'Sefer Kedushah',
            'Sefer Haflaah',
            'Sefer Zeraim',
            'Sefer Avodah',
            'Sefer Korbanot',
            'Sefer Taharah',
            'Sefer Nezikim',
            'Sefer Kinyan',
            'Sefer Mishpatim',
            'Sefer Shoftim',
        'Tur',
            'Beit Yosef',
            'Darchei Moshe',
            'Bach',
            'Prisha',
            'Drisha',
        'Shulchan Arukh',
        'Halakhot Gedolot',
        'Chayei Adam',
        'Chokhmat Adam',
        'Kitzur Shulchan Arukh',
        'Arukh HaShulchan',
        'Arukh HaShulchan HeAtid',
        'Ben Ish Hai',
        "Sifrei Mitzvot",
        "Issur v'Heter",
        "Geonim",
        "Rambam",
        "Rashba",
        "Other Rishonim",   #hack Because they both used the terms "Other Rishonim" and "Other Acharonim", we list Responsa subcats here.  #hack
        "Avodat HaKodesh (Chida)",
        "Monographs",
        "Radbaz",
        "Shoel uMeshiv",
        "Other Acharonim",
        "Peninei Halakhah",
        "B'Mareh HaBazak",
        "Contemporary Halakhic Problems",
        "Gray Matter",
        "Other Modern",
    "Kabbalah",
        "Sefer Yetzirah",
        "Hechalot Rabbati",
        "Sefer HaBahir",
        "Zohar",
        "Tikkunei Zohar",
        "Zohar Chadash",
        "Ramak",
        "Arizal / Chaim Vital",
        "Ramchal",
    'Liturgy',
        'Siddur',
        'Haggadah',
        'High Holidays',
        'Piyutim',
    "Jewish Thought",
        "Rishonim",
        "Maharal",
        "Acharonim",
        "Rav Kook",
        "Works of Eliezer Berkovits",
        "Modern",
    'Philosophy',   # todo: delete me after reorg
    "Tanaitic",     # todo: delete me after reorg
        "Tosefta",  # todo: move me after reorg
            "Seder Zeraim",
            "Seder Moed",
            "Seder Nashim",
            "Seder Nezikin",
            "Seder Kodashim",
            "Seder Tahorot",
        "Masechtot Ketanot",
    'Chasidut',
        "Early Works",
        "Breslov",
        "Izhbitz",
        "R' Tzadok HaKohen",
    'Musar',
    'Responsa',  # See list under Halacha
    'Second Temple',
        'Megillat Taanit'
        'Apocrypha',
        'Philo',
        'Josephus',
    'Modern Works',
    "Reference",
        "Dictionary",
        "Grammar",
    'Other',
    'Tosafot',  # Commentators
    'Bartenura',
    'Yachin',
    'Boaz'
]

TOP_CATEGORIES = [
    "Tanakh",
    "Mishnah",
    "Talmud",
    "Midrash",
    "Halakhah",
    "Kabbalah",
    "Liturgy",
    "Jewish Thought",
    "Tosefta"
    "Chasidut",
    "Musar",
    "Responsa",
    "Second Temple",
    "Reference",
]

REVERSE_ORDER = [
    'Commentary'  # Uch, STILL special casing commentary here... anything to be done??
]

