# Generated by OrchestKit Claude Plugin
# Created: 2026-06-30

# sefaria/system/tests/database_timeout_test.py
"""The global MongoClient must set finite socket/selection timeouts so a dead
Mongo TCP connection fails in minutes (and AutoReconnect retry recovers)
instead of hanging ~2h on OS TCP keepalive."""
import pytest
from sefaria.system import database


def test_timeout_kwargs_are_finite_and_sane():
    kw = database.MONGO_CLIENT_TIMEOUT_KWARGS
    # socketTimeoutMS bounds the dead-socket hang (was infinite/None)
    assert kw["socketTimeoutMS"] == 300_000
    # serverSelectionTimeoutMS waits through a full replica election
    assert kw["serverSelectionTimeoutMS"] == 60_000
    assert kw["connectTimeoutMS"] == 20_000


def test_live_client_has_timeouts_applied():
    # pymongo exposes resolved options on the client
    opts = database.client.options
    assert opts.pool_options.socket_timeout == 300.0          # seconds
    assert opts.server_selection_timeout == 60.0
    assert opts.pool_options.connect_timeout == 20.0
