# Generated by OrchestKit Claude Plugin
# Created: 2026-06-30

"""Unit tests for pure-logic functions in reindex_orchestrator.
Uses importlib to exec_module so heavy imports (kubernetes, django) are never triggered
— they live inside main() only."""
import importlib.util
import pathlib


spec = importlib.util.spec_from_file_location(
    "reindex_orchestrator",
    pathlib.Path("scripts/scheduled/reindex_orchestrator.py"),
)
orch = importlib.util.module_from_spec(spec)


def test_job_terminal_state():
    spec.loader.exec_module(orch)
    assert orch.job_terminal_state({"succeeded": 8, "failed": 0}, completions=8) == "complete"
    assert orch.job_terminal_state({"succeeded": 3, "failed": 1}, completions=8) is None
    assert orch.job_terminal_state({"succeeded": 5, "failed": 3}, completions=8, backoff_exhausted=True) == "failed"


def test_build_shard_job_manifest():
    spec.loader.exec_module(orch)
    manifest = orch.build_shard_job_manifest(
        name="test-job",
        namespace="default",
        image="my-image:latest",
        shard_count=4,
        command=["python", "run.py"],
    )
    assert manifest["apiVersion"] == "batch/v1"
    assert manifest["kind"] == "Job"
    assert manifest["spec"]["completionMode"] == "Indexed"
    assert manifest["spec"]["completions"] == 4
    assert manifest["spec"]["parallelism"] == 4
    assert manifest["spec"]["backoffLimitPerIndex"] == 2
    assert manifest["spec"]["maxFailedIndexes"] == 0
    # SHARD_COUNT env var appended
    env_names = [e["name"] for e in manifest["spec"]["template"]["spec"]["containers"][0]["env"]]
    assert "SHARD_COUNT" in env_names
    shard_count_val = next(e["value"] for e in manifest["spec"]["template"]["spec"]["containers"][0]["env"] if e["name"] == "SHARD_COUNT")
    assert shard_count_val == "4"
