# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-01-21 00:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0007_auto_20250527_0635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infocard',
            name='video_alt_en',
        ),
        migrations.RemoveField(
            model_name='infocard',
            name='video_alt_he',
        ),
    ] 