{{- if .Values.linker.enabled }}
{{- range $k, $v := untilStep (int (sub .Release.Revision .Values.previousServicesCount)) (int (add .Release.Revision 1)) 1 }}
{{- if gt $v 0 }}
---
apiVersion: v1
kind: Service
metadata:
  name: "linker-{{ $.Values.deployEnv }}-{{ $v }}"
  labels:
    app: linker-{{ $.Values.deployEnv }}
    deployEnv: "{{ $.Values.deployEnv }}"
    stackRole: linker
spec:
  ports:
  - port: 80
  selector:
    app: "linker-{{ $.Values.deployEnv }}"
    releaseRevision: "{{ $v }}"
{{- end }}
{{- end }}
{{- end }}
