{{- if or .Values.tasks.enabled .Values.gpuServer }}
apiVersion: v1
kind: Service
metadata:
  name: task-{{ .Values.deployEnv }}
  labels:
    app: tasks-{{ .Values.deployEnv }}
    deployEnv: "{{ .Values.deployEnv }}"
    stackRole: task
spec:
  ports:
  - port: 80
  selector:
    app: "tasks-{{ .Values.deployEnv }}"
{{- end }}
{{- if and (or .Values.tasks.enabled .Values.gpuServer) .Values.tasks.findRefs.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: find-refs-{{ .Values.deployEnv }}
  labels:
    app: find-refs-{{ .Values.deployEnv }}
    deployEnv: "{{ .Values.deployEnv }}"
    stackRole: task
spec:
  ports:
  - port: 80
  selector:
    app: "find-refs-{{ .Values.deployEnv }}"
{{- end }}
