{{- if or .Values.tasks.enabled .Values.tasks.gpuServer }}
apiVersion: v1
kind: Service
metadata:
  name: task-{{ .Values.deployEnv }}
  labels:
    app: tasks-{{ .Values.deployEnv }}
    deployEnv: "{{ .Values.deployEnv }}"
    stackRole: task
spec:
  ports:
  - port: 80
  selector:
    app: "tasks-{{ .Values.deployEnv }}"
{{- end }}
