apiVersion: v1
kind: Service
metadata:
  name: "varnish-{{ .Values.deployEnv }}"
  labels:
    app: varnish-{{ .Values.deployEnv }}
    deployEnv: "{{ .Values.deployEnv }}"
    stackRole: varnish
spec:
  ports:
  - name: http
    port: 8040
  - name: admin
    port: 6082
  {{- if .Values.varnish.monitoring.enabled }}
  - name: metrics
    port: 9131
    targetPort: metrics
  {{- end }}
  selector:
    app: varnish-{{ .Values.deployEnv }}
