# NB: This assumes an already-functioning elasticsearch instance.
---
{{- if .Values.restore.cleanup }}
apiVersion: batch/v1
kind: Job
metadata:
  name: destroy-elasticsearch-{{ .Values.deployEnv }}
  labels:
    deployEnv: {{ .Values.deployEnv | quote }}
    {{- include "sefaria.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: post-delete
    helm.sh/hook-delete-policy: hook-succeeded, hook-failed
    helm.sh/hook-weight: "10"
spec:
  template:
    spec:
      containers:
      - name: destroy-elasticsearch-{{ .Values.deployEnv }}
        image: "{{ .Values.web.containerImage.imageRegistry }}:{{ .Values.web.containerImage.tag }}"
        env:
        - name: SEARCH_HOST
          value: "elasticsearch-es-http.elasticsearch.svc"
        - name: SEARCH_PORT
          value: "9200"
        - name: SEARCH_PATH
          value: ""
        - name: SEARCH_SSL_ENABLE
          value: "false"
        envFrom:
        - secretRef:
            name: {{ template "sefaria.secrets.elasticAdmin" . }}
        - secretRef:
            name: {{ .Values.secrets.localSettings.ref }}
            optional: true
        - configMapRef:
            name: local-settings-{{ .Values.deployEnv }}
        - secretRef:
            name: local-settings-secrets-{{ .Values.deployEnv }}
            optional: true
        volumeMounts:
        - mountPath: /app/sefaria/local_settings.py
          name: local-settings
          subPath: local_settings.py
          readOnly: true
        command: ["bash"]
        args:
        - -c
        - "/app/run /app/scripts/scheduled/destroy_elasticsearch_cronjob.py"
      restartPolicy: Never
      volumes:
      - name: local-settings
        configMap:
          name: local-settings-file-{{ .Values.deployEnv }}
          items:
          - key: local_settings.py
            path: local_settings.py
  ttlSecondsAfterFinished: 432000
{{- end }}

