{{- if .Values.gateway.enabled }}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: {{ .Values.deployEnv }}
  labels:
    {{- include "sefaria.labels" . | nindent 4 }}
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: {{ .Values.deployEnv }}
  tls:
    alpnProtocols:
      - h2
      - http/1.1
{{- end }}
