{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.deployEnv }}
  labels:
    {{- include "sefaria.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ .Values.deployEnv }}
  hostnames:
    {{- range .Values.domains.root }}
    {{- $code := .code }}
    {{- if kindIs "slice" $code }}
      {{- $code = index $code 0 }}
    {{- end }}
    {{- $rootDomain := tpl .url $ | quote | trimAll "\"" }}
    {{- $wwwDomain := printf "www.%s" $rootDomain }}
        - {{ $rootDomain }}
        - {{ $wwwDomain }}
    {{- range $.Values.domains.modules }}
    {{- $subdomain := index .subdomains $code }}
    {{- if $subdomain }}
    {{- $subdomain := printf "%s.%s" $subdomain $rootDomain }}
        - {{ $subdomain }}
    {{- end }}
    {{- end }}
    {{- end }}
  rules:
    - backendRefs:
        - name: nginx-{{ $.Values.deployEnv }}
          port: 80
      matches:
        - path:
            type: PathPrefix
            value: /
{{- end }}
