{{- if .Values.secrets.elasticAdmin.data }}
apiVersion: v1
kind: Secret
metadata:
  name: elastic-admin-{{ .Values.deployEnv }}
  labels:
    deployEnv: "{{ .Values.deployEnv }}"
    {{- include "sefaria.labels" . | nindent 4 }}
type: Opaque
stringData: {{ .Values.secrets.elasticAdmin.data | toYaml | nindent 2 }}
{{- end }}
