{{- if .Values.web.secrets.elasticCertificate.data }}
apiVersion: v1
kind: Secret
metadata:
  name: elastic-certificate-{{ .Values.deployEnv }}
  labels:
    deployEnv: "{{ .Values.deployEnv }}"
    {{- include "sefaria.labels" . | nindent 4 }}
type: Opaque
data:
  ca.crt: {{ .Values.web.secrets.elasticCertificate.data | b64enc }}
{{- end }}
