{{- if .Values.secrets.localSettings.data }}
apiVersion: v1
kind: Secret
metadata:
  name: local-settings-secrets-{{ .Values.deployEnv }}
  labels:
    deployEnv: "{{ .Values.deployEnv }}"
    {{- include "sefaria.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $k, $v := .Values.secrets.localSettings.data }}
  {{ $k }}: {{ $v | b64enc }}
  {{- end }}
{{- end }}
