{{- if .Values.web.secrets.logging.data }}
apiVersion: v1
kind: Secret
metadata:
  name: logging-secret-{{ .Values.deployEnv }}
  labels:
    deployEnv: "{{ .Values.deployEnv }}"
    {{- include "sefaria.labels" . | nindent 4 }}
type: Opaque
data:
  logging-secret.json: {{ .Values.web.secrets.logging.data | b64enc }}
{{- end }}
