{{- if .Values.web.secrets.schoolLookup.data }}
apiVersion: v1
kind: Secret
metadata:
  name: school-lookup-data-{{ .Values.deployEnv }}
  labels:
    deployEnv: "{{ .Values.deployEnv }}"
    {{- include "sefaria.labels" . | nindent 4 }}
type: Opaque
data:
  schools.tsv: {{ .Values.web.secrets.schoolLookup.data | b64enc }}
{{- end }}
