{{- if .Values.secrets.slackWebhook.data }}
apiVersion: v1
kind: Secret
metadata:
  name: slack-webhook-{{ .Values.deployEnv }}
  labels:
    deployEnv: "{{ .Values.deployEnv }}"
    {{- include "sefaria.labels" . | nindent 4 }}
type: Opaque
data:
  slack-webhook: {{ .Values.secrets.slackWebhook.data | b64enc | quote }}
{{- end }}
