{{- if .Values.varnish.secrets.varnish.data }}
apiVersion: v1
kind: Secret
metadata:
  name: varnish-secret-{{ .Values.deployEnv }}
  labels:
    deployEnv: "{{ .Values.deployEnv }}"
    {{- include "sefaria.labels" . | nindent 4 }}
type: Opaque
data:
  varnish-secret: {{ .Values.varnish.secrets.varnish.data | b64enc }}
{{- end }}
