"""
analyze_base_text_cache_savings.py

Analyze how much prompt-caching of the base-text block would save for
disambiguation tasks generated by dispatch_library_links_disambiguation_tasks.py.

For each task we derive the base text (the source text a commentary is
discussing), then group tasks that share the same base ref and report:
  - How many groups there are
  - How many tasks are in each group
  - How many tokens the base text block is for that group

Token counts use the Anthropic API (client.messages.count_tokens, claude-sonnet-4-5).

Usage:
    ./run scripts/analyze_base_text_cache_savings.py [--cache-suffix SUFFIX]

    --cache-suffix  Suffix appended to cache filenames (default: 100).
                    Use 2000 to analyze the larger cached sample.
"""

import django
django.setup()

import argparse
import json
import logging
import os
from collections import defaultdict
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import asdict

import anthropic
from tqdm import tqdm

logging.getLogger("httpx").setLevel(logging.WARNING)

from sefaria.helper.linker.disambiguator import (
    AmbiguousResolutionPayload,
    NonSegmentResolutionPayload,
    _get_commentary_base_context,
    _format_base_block,
)

DEBUG_CACHE_DIR = os.path.join(os.path.dirname(__file__), "debug_cache")

_CLIENT = anthropic.Anthropic()
_COUNT_TOKENS_MODEL = "claude-sonnet-4-5"
CACHE_MIN_TOKENS = 1024  # Sonnet 4.5 minimum cacheable block size


def _count_tokens(text: str) -> int:
    response = _CLIENT.messages.count_tokens(
        model=_COUNT_TOKENS_MODEL,
        messages=[{"role": "user", "content": text}],
    )
    return response.input_tokens


def _load_cache(name: str, suffix: str) -> list:
    path = os.path.join(DEBUG_CACHE_DIR, f"{name}_{suffix}.json")
    if not os.path.exists(path):
        print(f"  Cache file not found: {path}")
        return []
    with open(path) as f:
        return json.load(f)


def _build_ambiguous_payloads(docs: list) -> list[AmbiguousResolutionPayload]:
    payloads = []
    for doc in docs:
        for span in doc.get("spans", []):
            if not (span.get("ambiguous") and span.get("type") == "citation"):
                continue
            ref_str = span.get("ref")
            if not ref_str:
                continue
            payloads.append(AmbiguousResolutionPayload(
                ref=doc["ref"],
                versionTitle=doc.get("versionTitle", ""),
                language=doc.get("language", ""),
                charRange=span.get("charRange", [0, 0]),
                text=span.get("text", ""),
                ambiguous_refs=[ref_str],
            ))
    return payloads


def _build_non_segment_payloads(docs: list) -> list[NonSegmentResolutionPayload]:
    payloads = []
    for doc in docs:
        for span in doc.get("spans", []):
            if span.get("type") != "citation" or span.get("failed"):
                continue
            ref_str = span.get("ref")
            if not ref_str:
                continue
            payloads.append(NonSegmentResolutionPayload(
                ref=doc["ref"],
                versionTitle=doc.get("versionTitle", ""),
                language=doc.get("language", ""),
                charRange=span.get("charRange", [0, 0]),
                text=span.get("text", ""),
                resolved_non_segment_ref=ref_str,
            ))
    return payloads


def analyze(suffix: str) -> None:
    print(f"\n=== Base-text cache savings analysis (cache suffix: {suffix}) ===\n")

    amb_docs = _load_cache("ambiguous", suffix)
    ns_docs = _load_cache("non_segment", suffix)
    print(f"Loaded {len(amb_docs)} ambiguous docs, {len(ns_docs)} non-segment docs")

    amb_payloads = _build_ambiguous_payloads(amb_docs)
    ns_payloads = _build_non_segment_payloads(ns_docs)
    all_payloads = amb_payloads + ns_payloads
    print(f"Built {len(amb_payloads)} ambiguous payloads + {len(ns_payloads)} non-segment payloads = {len(all_payloads)} total\n")

    # Pass 1: collect unique base refs and count tasks
    print("Collecting base refs for all tasks...")
    base_blocks: dict[str, str] = {}   # base_ref -> formatted block text
    task_counts: dict[str, int] = defaultdict(int)
    no_base_text_count = 0

    for payload in all_payloads:
        base_ref, base_text = _get_commentary_base_context(payload.ref)
        if not base_ref or not base_text:
            no_base_text_count += 1
            continue
        if base_ref not in base_blocks:
            base_blocks[base_ref] = _format_base_block(base_ref, base_text)
        task_counts[base_ref] += 1

    print(f"  Found {len(base_blocks)} unique base refs; counting tokens with 50 threads...")

    # Pass 2: count tokens in parallel
    token_counts: dict[str, int] = {}
    with ThreadPoolExecutor(max_workers=50) as executor:
        futures = {executor.submit(_count_tokens, block): ref for ref, block in base_blocks.items()}
        for future in tqdm(as_completed(futures), total=len(futures), desc="Counting tokens"):
            token_counts[futures[future]] = future.result()

    groups: dict[str, dict] = {
        ref: {
            "tasks": task_counts[ref],
            "base_block_tokens": token_counts[ref],
            "base_block_chars": len(base_blocks[ref]),
        }
        for ref in base_blocks
    }

    print(f"  Tasks with no base text: {no_base_text_count}")
    print(f"  Unique base refs (groups): {len(groups)}\n")

    if not groups:
        print("No groups found.")
        return

    # Sort by task count descending
    sorted_groups = sorted(groups.items(), key=lambda x: x[1]["tasks"], reverse=True)

    # --- Summary stats ---
    total_tasks_with_base = sum(g["tasks"] for _, g in sorted_groups)
    total_groups = len(sorted_groups)
    all_token_counts = [g["base_block_tokens"] for _, g in sorted_groups]

    cacheable_groups   = [(r, g) for r, g in sorted_groups if g["base_block_tokens"] >= CACHE_MIN_TOKENS and g["tasks"] > 1]
    uncacheable_groups = [(r, g) for r, g in sorted_groups if g["base_block_tokens"] < CACHE_MIN_TOKENS]

    total_tokens_uncached = sum(g["base_block_tokens"] * g["tasks"] for _, g in sorted_groups)
    # With caching: cacheable groups pay once; uncacheable groups pay every time
    total_tokens_with_cache = (
        sum(g["base_block_tokens"] for _, g in cacheable_groups) +
        sum(g["base_block_tokens"] * g["tasks"] for _, g in uncacheable_groups) +
        sum(g["base_block_tokens"] * g["tasks"] for _, g in sorted_groups
            if g["base_block_tokens"] >= CACHE_MIN_TOKENS and g["tasks"] == 1)
    )
    tokens_saved = total_tokens_uncached - total_tokens_with_cache

    print("=== Summary ===")
    print(f"  Total tasks with a base text:            {total_tasks_with_base}")
    print(f"  Unique base refs (groups):               {total_groups}")
    print(f"  Groups >= {CACHE_MIN_TOKENS} tokens (cacheable):      {len(cacheable_groups) + sum(1 for _, g in sorted_groups if g['base_block_tokens'] >= CACHE_MIN_TOKENS and g['tasks'] == 1)}")
    print(f"  Groups >= {CACHE_MIN_TOKENS} tokens AND >1 task:      {len(cacheable_groups)}")
    print(f"  Groups < {CACHE_MIN_TOKENS} tokens (never cached):    {len(uncacheable_groups)}")
    print(f"  Avg tasks per group:                     {total_tasks_with_base / total_groups:.1f}")
    print(f"  Avg base-block tokens:                   {sum(all_token_counts) / total_groups:.0f}")
    print(f"  Min / max base-block tokens:             {min(all_token_counts)} / {max(all_token_counts)}")
    print()
    print(f"  Total base-text tokens (no caching):     {total_tokens_uncached:,}")
    print(f"  Total base-text tokens (with caching):   {total_tokens_with_cache:,}")
    print(f"  Tokens saved by caching:                 {tokens_saved:,}  ({100*tokens_saved/total_tokens_uncached:.1f}% reduction)")
    print()

    # --- Per-group table (top 30) ---
    print(f"=== Top 30 groups by task count  [* = below {CACHE_MIN_TOKENS}-token cache minimum] ===")
    print(f"{'Base ref':<55} {'Tasks':>6} {'Tokens':>8} {'Saved':>8}")
    print("-" * 82)
    for base_ref, g in sorted_groups[:30]:
        cacheable = g["base_block_tokens"] >= CACHE_MIN_TOKENS and g["tasks"] > 1
        saved = g["base_block_tokens"] * (g["tasks"] - 1) if cacheable else 0
        flag = "  " if cacheable else " *"
        print(f"{base_ref:<55}{flag} {g['tasks']:>4} {g['base_block_tokens']:>8,} {saved:>8,}")

    if len(sorted_groups) > 30:
        remainder = sorted_groups[30:]
        r_tasks = sum(g["tasks"] for _, g in remainder)
        r_saved = sum(
            g["base_block_tokens"] * (g["tasks"] - 1)
            for _, g in remainder
            if g["base_block_tokens"] >= CACHE_MIN_TOKENS and g["tasks"] > 1
        )
        print(f"{'... (' + str(len(remainder)) + ' more groups)':<55} {'':>2} {r_tasks:>4} {'':>8} {r_saved:>8,}")

    print()

    # --- Distribution of group sizes ---
    size_dist: dict[int, int] = defaultdict(int)
    for _, g in sorted_groups:
        size_dist[g["tasks"]] += 1
    print("=== Distribution of group sizes (tasks sharing same base text) ===")
    print(f"{'Tasks in group':>16} {'# groups':>10} {'% of groups':>12}")
    print("-" * 42)
    for size in sorted(size_dist):
        pct = 100 * size_dist[size] / total_groups
        print(f"{size:>16} {size_dist[size]:>10} {pct:>11.1f}%")


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--cache-suffix", default="2000", help="Cache file suffix (default: 100)")
    args = parser.parse_args()
    analyze(args.cache_suffix)


if __name__ == "__main__":
    main()
