# -*- coding: utf-8 -*-

from sefaria.utils.user import markEmailPattern, markGroup, markUserByEmail

markEmailPattern("westchesterday.org", "Westchester Day", "Student 2016", False)
markEmailPattern("mhafyos.org", "Margolin Hebrew Academy", "Student 2016", False)
markEmailPattern("milkenschool.org", "Milken", "Student 2016", False)
markEmailPattern("icja.org", "ICJA", "Student 2015", False)
markEmailPattern("sarhighschool.org", "SAR", "Student 2015", False)
markEmailPattern("frisch.org", "Frisch"	, "Student 2016", False)
markEmailPattern("btfiloh.org", "Beth Tefiloh Dahan", "Student 2015", False)
markEmailPattern("ohds.org", "Oakland Hebrew Day", "Student 2015", False)

markGroup('Margolin Hebrew Academy Parsha', "Margolin Hebrew Academy", "Student 2016", False)

markGroup('Hillel Educators', "Hillel International", "Teacher 2016", False)

markEmailPattern("schechter.org", "SSDS Chicago", "Teacher 2016", False)
markEmailPattern("heschel.org", "Heschel", "Teacher 2016", False)
markEmailPattern("schechterwestchester.org", "SSDS Westchester", "Teacher 2016", False)

markUserByEmail("agreenberg@westchesterday.org", "Westchester Day", "Teacher 2016", False)
markUserByEmail("rabbinachbar@gmail.com", "Margolin Hebrew Academy", "Teacher 2016", False)
markUserByEmail("moshe.nachbar@mhafyos.org", "Margolin Hebrew Academy", "Teacher 2016", False)
markUserByEmail("moshesemmel@gmail.com", "Margolin Hebrew Academy", "Teacher 2016", False)
markUserByEmail("leora.klein@mhafyos.org", "Margolin Hebrew Academy", "Teacher 2016", False)
markUserByEmail("anatkampf@mhafyos.org", "Margolin Hebrew Academy", "Teacher 2016", False)
markUserByEmail("baruchharris3@gmail.com", "Margolin Hebrew Academy", "Teacher 2016", False)
markUserByEmail("bcohen@milkenschool.org", "Milken", "Teacher 2016", False)
markUserByEmail("billcohen64@gmail.com", "Milken", "Teacher 2016", False)
markUserByEmail("william.cohen@comcast.net", "Milken", "Teacher 2016", False)
markUserByEmail("sfields-meyer@milkenschool.org", "Milken", "Teacher 2016", False)
markUserByEmail("davidjsaiger@gmail.com", "Milken", "Teacher 2016", False)
markUserByEmail("bsegal@icja.org", "ICJA", "Teacher 2015", False)
markUserByEmail("ofriedman@icja.org", "ICJA", "Teacher 2015", False)
markUserByEmail("sarawolkenfeld@gmail.com", "ICJA", "Teacher 2015", False)
markUserByEmail("ylindenbaum@sarhighschool.org", "SAR", "Teacher 2015", False)
markUserByEmail("avi.bloom@gmail.com", "SAR", "Teacher 2015", False)
markUserByEmail("hbroder@gmail.com", "SAR", "Teacher 2015", False)
markUserByEmail("Betsy.forester@schechter.org", "SSDS Chicago", "Teacher 2016", False)
markUserByEmail("shiri.aharonovich@schechter.org", "SSDS Chicago", "Teacher 2016", False)
markUserByEmail("ron.schrag@schechter.org", "SSDS Chicago", "Teacher 2016", False)
markUserByEmail("effiekleinberg@gmail.com", "B'nai Akiva Schools", "Teacher 2016", False)
markUserByEmail("akiva.friedman@gmail.com", "B'nai Akiva Schools", "Teacher 2016", False)
markUserByEmail("akiva.friedman@melamedacademy.com", "B'nai Akiva Schools", "Teacher 2016", False)
markUserByEmail("ygelernter@gmail.com", "B'nai Akiva Schools", "Teacher 2016", False)
markUserByEmail("tzvi.h18@gmail.com", "Gindi Maimonides", "Teacher 2016", False)
markUserByEmail("heatherk314@gmail.com", "Austin Jewish Acadmey", "Teacher 2015", False)
markUserByEmail("ariellafalack@gmail.com", "Magen David", "Teacher 2015", False)
markUserByEmail("asutton@mdyhs.net", "Magen David", "Teacher 2015", False)
markUserByEmail("yael.goldfischer@frisch.org", "Frisch", "Teacher 2016", False)
markUserByEmail("Tzvi.Pittinsky@frisch.org", "Frisch", "Teacher 2016", False)
markUserByEmail("naomizaslow@gmail.com", "SSDS of Boston", "Teacher 2016", False)
markUserByEmail("dan.savitt@ssdsboston.org", "SSDS of Boston", "Teacher 2016", False)
markUserByEmail("satoritai@gmail.com", "SSDS of Boston", "Teacher 2016", False)
markUserByEmail("lianne.gross@ssdsboston.org", "SSDS of Boston", "Teacher 2016", False)
markUserByEmail("dovne@heschel.org", "Heschel", "Teacher 2016", False)
markUserByEmail("raskas.elana@gmail.com", "YUHS (Central)", "Teacher 2016", False)
markUserByEmail("tkaplowitz@btfiloh.org", "Beth Tefiloh Dahan", "Teacher 2015", False)
markUserByEmail("rabbidweck@gmail.com", "Gindi Barkai", "Teacher 2015", False)
markUserByEmail("bmiller@ohds.org", "Oakland Hebrew Day", "Teacher 2015", False)
markUserByEmail("batmiller@gmail.com", "Oakland Hebrew Day", "Teacher 2015", False)
markUserByEmail("mimifarb@gmail.com", "Oakland Hebrew Day", "Teacher 2015", False)
markUserByEmail("tbeliak@ohds.org", "Oakland Hebrew Day", "Teacher 2015", False)
markUserByEmail("ogoldberg@ohds.org", "Oakland Hebrew Day", "Teacher 2015", False)
markUserByEmail("egoldberg@ohds.org", "Oakland Hebrew Day", "Teacher 2015", False)
markUserByEmail("jcahan@schechterwestchester.org", "SSDS Westchester", "Teacher 2016", False)
markUserByEmail("p.eckstein@cjepb.org", "Friedman Commission for Jewish Education", "Teacher 2016", False)
markUserByEmail("ppeteck18@gmail.com", "Friedman Commission for Jewish Education", "Teacher 2016", False)
markUserByEmail("terrapin@mindspring.com", "Friedman Commission for Jewish Education", "Teacher 2016", False)
markUserByEmail("l.lieberman@cjepb.org", "Friedman Commission for Jewish Education", "Teacher 2016", False)
markUserByEmail("r.hurvitz@cjepb.org", "Friedman Commission for Jewish Education", "Teacher 2016", False)
markUserByEmail("dbash@ou.org", "NCSY", "Teacher 2016", False)
markUserByEmail("sari.borenstein@gmail.com", "NCSY", "Teacher 2016", False)
markUserByEmail("avivag@pardes.org.il", "Pardes", "Teacher 2016", False)
markUserByEmail("avivagolbert@gmail.com", "Pardes", "Teacher 2016", False)
markUserByEmail("gbecker@jewishlearningventure.org", "Jewish Learning Venture", "Teacher 2016", False)
markUserByEmail("hinda@eisen.us", "Ohr Kodesh", "Teacher 2016", False)
markUserByEmail("lylefishman@gmail.com", "Ohr Kodesh", "Teacher 2016", False)
markUserByEmail("andy.weissfeld@gmail.com", "Ohr Kodesh", "Teacher 2016", False)
markUserByEmail("jessica.b.woolf@gmail.com", "Ohr Kodesh", "Teacher 2016", False)
markUserByEmail("melissa.ser@gmail.com", "Adat Shalom", "Teacher 2016", False)
markUserByEmail("ravabergman@gmail.com", "Adat Shalom", "Teacher 2016", False)
markUserByEmail("hazzangross@gmail.com", "Adat Shalom", "Teacher 2016", False)
markUserByEmail("jgross@adatshalom.org", "Adat Shalom", "Teacher 2016", False)
markUserByEmail("mwitman80@gmail.com", "B'nai Jeshurun", "Teacher 2016", False)
markUserByEmail("sarahalevsky@gmail.com", "Kivun", "Teacher 2016", False)
markUserByEmail("cabrams@wornickjds.org", "JDS of Seattle", "PCJE Tanakh Teacher 2016", False)
markUserByEmail("cabramssimonton@gmail.com", "JDS of Seattle", "PCJE Tanakh Teacher 2016", False)
markUserByEmail("java4nechama@yahoo.com", "JPDS", "PCJE Tanakh Teacher 2016", False)
markUserByEmail("perlis.hannah@gmail.com", "Carmel Academy", "PCJE Tanakh Teacher 2016", False)
markUserByEmail("anna10banana@gmail.com", "Chicago JDS", "PCJE Tanakh Teacher 2016", False)
markUserByEmail("drosenbaum@cesjds.org", "Charles E Smith", "PCJE Tanakh Teacher 2016", False)
markUserByEmail("lrubins@schechterwestchester.org", "SSDS Westchester", "PCJE Tanakh Teacher 2016", False)
markUserByEmail("jsacks@dths.org", "de Toledo HS", "PCJE Tanakh Teacher 2016", False)
markUserByEmail("andersonnatan0@gmail.com", "Pardes student", "Teacher 2016", False)
markUserByEmail("ohbieder@gmail.com", "Pardes student", "Teacher 2016", False)
markUserByEmail("adamhenryjosephs@gmail.com", "Pardes student", "Teacher 2016", False)
markUserByEmail("skorelitz@yahoo.com", "Pardes student", "Teacher 2016", False)
markUserByEmail("avimandel28@gmail.com", "Pardes student", "Teacher 2016", False)
markUserByEmail("anir117@hotmail.com", "Pardes student", "Teacher 2016", False)
markUserByEmail("jonah.naftali@gmail.com", "Pardes student", "Teacher 2016", False)

