#!/usr/bin/env bash
# Test runner for scripts
# Currently just runs listed scripts and show any error messages.

ouput=""

run_test () {
    echo $1
    result="$(cd ../..; ./run $1)"
    [[ -z "$result" ]] && result="FAIL" || result="PASS" # not working
    output+="$1 - $result\n"    
}

run_test "metrics.py"
run_test "leaderboards.py"
run_test "send_email_notifications.py all"
run_test "update_sheet_ref_index.py 1"
run_test "index_from_queue.py"


#echo -e "\n\n***** RESULTS ******"
#echo -e $output
