# Generated by OrchestKit Claude Plugin
# Created: 2026-06-30

#!/usr/bin/env python
"""Reindex orchestrator: init -> Indexed Job (N shards) -> finalize.
Runs as the weekly CronJob. Holds no ES/Mongo connection during the shard phase."""
import os
import sys
import time
import logging

logger = logging.getLogger(__name__)


def job_terminal_state(status, completions, backoff_exhausted=False):
    """Returns 'complete', 'failed', or None (still running).
    Pure function — no I/O, no imports beyond builtins.
    """
    if status.get("succeeded", 0) >= completions:
        return "complete"
    if backoff_exhausted:
        return "failed"
    return None


def build_shard_job_manifest(name, namespace, image, shard_count, command, env=None, resources=None):
    """Build a batch/v1 Indexed Job manifest as a plain dict.
    Pure function — no I/O, no imports beyond builtins.
    """
    return {
        "apiVersion": "batch/v1",
        "kind": "Job",
        "metadata": {"name": name, "namespace": namespace},
        "spec": {
            "completionMode": "Indexed",
            "completions": shard_count,
            "parallelism": shard_count,
            "backoffLimitPerIndex": 2,
            "maxFailedIndexes": 0,
            "ttlSecondsAfterFinished": 86400,
            "template": {
                "spec": {
                    "restartPolicy": "Never",
                    "containers": [
                        {
                            "name": "reindex-shard",
                            "image": image,
                            "command": command,
                            "env": (env or []) + [{"name": "SHARD_COUNT", "value": str(shard_count)}],
                            "resources": resources or {
                                "requests": {"memory": "8Gi"},
                                "limits": {"memory": "12Gi"},
                            },
                        }
                    ],
                }
            },
        },
    }


def main():
    # Heavy imports are lazy so unit tests can exec_module without these packages
    import django
    django.setup()
    from kubernetes import client, config
    from sefaria.search import reindex_init, reindex_finalize, reindex_index_shard
    from sefaria.pagesheetrank import update_pagesheetrank

    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")

    config.load_incluster_config()
    namespace = os.environ["K8S_NAMESPACE"]
    shard_count = int(os.environ.get("SHARD_COUNT", "8"))
    image = os.environ["SHARD_JOB_IMAGE"]
    job_name = os.environ.get("SHARD_JOB_NAME", "reindex-shard")
    command = [
        "bash", "-c",
        "python /app/scripts/scheduled/reindex_elasticsearch_cronjob.py --mode shard --type text",
    ]

    batch = client.BatchV1Api()

    # 1. INIT — pagesheetrank + create indexes
    logger.info("Orchestrator: running init (pagesheetrank + create indexes)")
    update_pagesheetrank()
    reindex_init("text")
    reindex_init("sheet")

    # 2. Delete stale job if present, then create the Indexed Job
    try:
        batch.delete_namespaced_job(job_name, namespace, propagation_policy="Background")
        time.sleep(10)
    except client.exceptions.ApiException:
        pass

    manifest = build_shard_job_manifest(job_name, namespace, image, shard_count, command)
    batch.create_namespaced_job(namespace, manifest)
    logger.info(f"Orchestrator: created Indexed Job {job_name} with {shard_count} shards")

    # 3. Poll until terminal state — holds NO ES/Mongo connection here
    while True:
        job = batch.read_namespaced_job_status(job_name, namespace)
        st = job.status
        status = {"succeeded": st.succeeded or 0, "failed": st.failed or 0}
        backoff_exhausted = bool(getattr(st, "conditions", None)) and any(
            c.type == "Failed" and c.status == "True" for c in st.conditions
        )
        state = job_terminal_state(status, shard_count, backoff_exhausted)
        logger.info(f"Orchestrator: shard job status={status}, state={state}")
        if state == "complete":
            break
        if state == "failed":
            logger.error("Orchestrator: shard job failed; NOT finalizing (alias unchanged)")
            sys.exit(1)
        time.sleep(60)

    # 4. FINALIZE — restore settings, sanity gate, alias swap; then sheets
    logger.info("Orchestrator: all shards complete; finalizing")
    reindex_finalize("text")
    reindex_index_shard("sheet")
    reindex_finalize("sheet")
    logger.info("Orchestrator: reindex complete")


if __name__ == "__main__":
    main()
