"""Hardening audit 2026-10-05 (phone User-Agent probes of the reader, banner geometry). Idempotent."""
import json, pathlib
T = pathlib.Path(__file__).resolve().parents[1]
atlas = json.load(open(T / "features.json")); by = {f["id"]: f for f in atlas}
def add(fid, lines):
    for l in lines:
        if l not in by[fid]["details"]: by[fid]["details"].append(l)
add("SHL-062", ["VERIFIED 2026-10-05 with a phone User-Agent (iPhone, 390px): the site header is hidden while reading; the panel's own header has, left to right, a hamburger (opens the site's mobile navigation menu, which then shows over the text), the title + version, a bookmark (Save) and the display 'A'. Rebuild: menu button in the panel header (CSS swaps it with Close at ≤842px), shared open/closed state (features/shell/mobile-menu.ts), the menu closes on navigation and Escape.",
             "FOUND: the earlier phone parity runs used a desktop User-Agent at 390px, and sefaria.org decides single-panel mode from the User-Agent, so the phone-only rules were never seen. Re-probe phone behaviour with a phone UA (see scripts/parity-search.mjs --mobile)."])
add("SHL-074", ["VERIFIED: the text header has a Save button (aria-label 'Save \"Genesis 1\"', a bookmark) before the display-options 'A'. Signed out it opens the 'Want to return to this text?' sign-up modal (Save texts / Take notes / View your reading history / Build & share source sheets; Sign Up, Already have an account? Sign in). Rebuild: built (it was missing); the modal is the existing 'save' kind."])
add("TXD-040", ["VERIFIED on a phone UA: `.singlePanel .basetext .text { padding: 0 34px }` — the text runs from x=34 to x=356 at 390px (322px wide), Hebrew right-aligned inside justified paragraphs; with a desktop UA at the same width it is x=56 (narrowColumn). Rebuild: 34px under (max-width: 842px) and (pointer: coarse)."])
add("SHL-025", ["FOUND 2026-10-05: sefaria.org decides single-panel mode from the User-Agent, not the width — a desktop browser squeezed to 390px keeps desktop rules (text x=56, sort dropdown on the Books tab) while a phone UA gets the phone rules (text x=34, filter button). The rebuild decides by width (≤842px) and, for the 34px text padding, by a coarse pointer."])
add("VER-004", ["VERIFIED 2026-10-05 geometry of the 'Want to change the translation? [Go to translations] ×' banner: 60px tall, grey #ededec across the panel, 16px #666 text (the bold word too), content centred in the 760px reading column with 30px sides, white buttons (padding 5px 11px, radius 6px, 16px #666), a 35px #bbb × at the column's end. On a phone UA the text wraps to two lines and the button text to two (125px wide). Rebuild: restyled to these values (it was 14px, different grey, × at the screen edge)."])
json.dump(atlas, open(T / "features.json", "w"), ensure_ascii=False, indent=1)
S2 = T / "rebuild-status.json"; st = json.load(open(S2))
st["SHL-062"] = {"status": "done", "by": "src/features/reader/TextPanel.tsx, src/features/shell/mobile-menu.ts"}
json.dump(st, open(S2, "w"), ensure_ascii=False, indent=1)
atlas = json.load(open(T / "features.json")); by = {f["id"]: f for f in atlas}
def add(fid, lines):
    for l in lines:
        if l not in by[fid]["details"]: by[fid]["details"].append(l)
add("BOK-002", ["VERIFIED 2026-10-05 geometry (desktop): title 30px Cardo #000; category 14px Roboto #6f6f6f, letter-spacing 1px, upper-case; the edition credit is 24px italic Cardo #666, NOT a small underlined link; Start Reading 124×39 (padding 10px 14px, 16px); Contents/Versions tabs 22px; group titles 24px black with a small grey chevron AFTER the title. A language button (aleph; 34×34, 1px #ccc border) sits at the column's end. Rebuild matched (it had 14px credit and the chevron first).",
             "VERIFIED on a phone UA: the site header stays on a book page (only texts hide it); the composition line and description sit under Start Reading, there is no 'About This Text' module."])
add("BOK-006", ["VERIFIED: the sidebar module lists, above the description, 'Author(s): <links to /topics/slug>' and 'Composed: <place>, <date>' (parentheses removed, double spaces collapsed; none for Tanakh's Torah/Prophets/Writings); labels grey, values black. The rebuild's sidebar had only the description — fixed (src/lib/book/about-text.ts)."])
add("LIB-036", ["Rebuilt for the book page (see BOK-006). Not yet for the reader sidebar's own About box, which has its own wording (CON-039)."])
add("LIB-002", ["VERIFIED: the aleph/ayin language button also sits on /texts, category pages and book pages (not in the Hebrew interface). It turns that page's CONTENT to Hebrew — titles, ordering, numerals (ב. ב: ג.), right-to-left, tabs mirrored — without changing the site's language or the address; the second icon is the English 'A'. Rebuild: ContentLanguage (state in the page; icons from the old site)."])
add("LIB-004", ["VERIFIED with a phone UA: the About blurb ('Sefaria is home to 3,000 years of Jewish texts … Learn More ›') sits under 'Browse the Library' on /texts. Rebuilt (AboutBlurb, shown at ≤842px). Still open: the Recently Viewed list (needs the reader's history)."])
add("LIB-008", ["FOUND with a phone UA: category pages show the category's long description inline (and no 'About <category>' module); on a Talmud page the live text is the longer 'The Talmud (literally, “study”) is the textual record…', ours is the shorter sidebar text. Not yet rebuilt (phone only)."])
json.dump(atlas, open(T / "features.json", "w"), ensure_ascii=False, indent=1)
atlas = json.load(open(T / "features.json")); by = {f["id"]: f for f in atlas}
add("GUI-003", ["VERIFIED 2026-10-05 geometry (1280px): header 60px, 30px sides; logo 154×25; Texts/Topics/Donate 16px/500 #666 at x=244/313/391 (60px after the logo, 30px apart, no boxes); search 250×30 (pill, 18px input) → 20px → Sign Up 74×28 (padding 6px 12px) → 20px → four 18px icons 20px apart ending at x=1250. Rebuild matched (it had 34px-tall controls and padded link boxes).",
             "FOUND: the site header's menus (language, Library, account) opened UNDER the reader's sticky panel header (z-index 100 vs 20), hiding their items; the header is now z-index 110."])
json.dump(atlas, open(T / "features.json", "w"), ensure_ascii=False, indent=1)
atlas = json.load(open(T / "features.json")); by = {f["id"]: f for f in atlas}
add("CON-070", ["FOUND 2026-10-05: this entry (and CON-003) was marked done, but the sidebar header had no language toggle. VERIFIED on sefaria.org: the header is #ededed, 60px, 34px sides; title 16px weight-100 (light) #666 with 1px letter-spacing, upper-case; at the right an aleph/ayin button (18px, 40% grey; shows the language it will switch TO) and the circled × (20px). It sets `lang2` (the sidebar's own language) and never touches the text's. Rebuilt (ConnectionsPanel `lang`/`onLang`, TextPanel `onSidebarLang`)."])
add("CON-016", ["VERIFIED geometry: tool and resource rows (About this Text, Table of Contents, Search in this Text, Translations, Sheets, Web Pages, Topics, Manuscripts, Torah Readings…) are Roboto 16px black with 1px letter-spacing, 18px icons (#6f6f6f), counts light (weight 100) #666; every row is 41px apart; category rows are Cardo 18px. Content starts 49px in from the sidebar's edge. Rebuilt (FilterRow `tool`)."])
json.dump(atlas, open(T / "features.json", "w"), ensure_ascii=False, indent=1)
atlas = json.load(open(T / "features.json")); by = {f["id"]: f for f in atlas}
add("SHL-074", ["VERIFIED geometry (1280px, no sidebar): the text header's controls sit inside the text's own 700px column (Close at x=290, title centred at 640, Save at 932, display 'A' at 969), not at the panel's edges; title 18px Cardo, version line 15px italic #6f6f6f; the bar is 60px under a 4px category colour line. Rebuilt (the bar was full-width with a 13px subtitle)."])
json.dump(atlas, open(T / "features.json", "w"), ensure_ascii=False, indent=1)
atlas = json.load(open(T / "features.json")); by = {f["id"]: f for f in atlas}
add("TXD-041", ["VERIFIED 2026-10-05 (sefaria.org desktop, Genesis, bilingual): the display menu is a 258px white card (radius 5, 14px Roboto): 1) THREE full-width rows, 235×35 radius 6, 'Source' / 'Translation' / 'Source with Translation', the chosen one #18345d with white text, a 20px radio circle at the end (aria group 'Source-translation toggle'); 2) rule; 3) 'Layout' + three 36×32 icon tiles (aria 'Show Source & Translation Stacked', 'Show RTL Text Left of LTR Text', 'Show RTL Text Right of LTR Text'), the chosen one dark; 4) 'Aliyot' switch (46×24 pill); 5) rule; 6) ⊖ 'Font Size' ⊕ (24px circled icons, no percentage); 7) rule; 8) 'Vowels' and 'Cantillation' switches. Order: language, layout, aliyot, font size, vowels, cantillation. Hovering the trigger shows the tooltip 'Text display options'. Rebuilt to this (it was a segmented Source/Translation/Both with headings and a Stepper; the Stepper component is removed).",
             "Not yet: the hover tooltip on the trigger; the Hebrew-interface strings were not re-verified."])
add("TXD-031", ["Rebuild: the third option reads 'Source with Translation' (not 'Both')."])
json.dump(atlas, open(T / "features.json", "w"), ensure_ascii=False, indent=1)
atlas = json.load(open(T / "features.json")); by = {f["id"]: f for f in atlas}
add("BOK-009", ["VERIFIED 2026-10-05 (sidebar Table of Contents, Genesis, desktop): 50×50 WHITE tiles with 6px gaps (5 per row in the 300px column), 18px serif numbers in black, the reader's place a filled #18345d tile with white number; headings 'Chapters' / 'Torah Portions' 16px #666 sans. Rebuilt (it had small bordered tiles in sans)."])
add("VER-009", ["VERIFIED typography: intro 16px #666; language heading 'English (14)' mixed case, 16px, letter-spacing 1px, count weight 100; previews 18px/22px black serif; ONE 14px grey line under each: '⌄ <italic title> • Select' (or '• Currently Selected'), the © mark after it when licensed. Rebuilt."])
json.dump(atlas, open(T / "features.json", "w"), ensure_ascii=False, indent=1)
atlas = json.load(open(T / "features.json")); by = {f["id"]: f for f in atlas}
add("CON-030", ["VERIFIED 2026-10-05 geometry of the connected-texts list: title 18px black UPPER-CASE with a 4px rule (#4b71b7 for commentary, the category's colour otherwise) under the title's own width; each item a block ruled 1px #eee below: the source in 18px grey (#6f6f6f) serif, the text 18px/25px JUSTIFIED black, and '⧉ Open' in 14px grey sans (an external-link icon, not a blue button). Empty: italic 14px 'No connections known for Rashi here.' (Hebrew 'אין קשרים ידועים ל<name>.'), under the category's rule colour even when this verse has none. Rebuilt."])
json.dump(atlas, open(T / "features.json", "w"), ensure_ascii=False, indent=1)
atlas = json.load(open(T / "features.json")); by = {f["id"]: f for f in atlas}
add("CON-007", ["VERIFIED 2026-10-05: choosing Share (and Feedback, and the other sign-in/tool modes) on sefaria.org does NOT change the address except for `lang2=en` added when the sidebar opens (`with=all` stays); opening `/…?with=Share` there is read as a text FILTER and shows 'No connections known for Share here.' (title SHARE, green rule). Rebuild deliberately differs: Share, Feedback, Advanced Tools, Translations… have their own `with=` values so a view survives a reload and can be linked; an old-site reader opening such a link sees the filter message. Also not done: the `lang2=en` the old site appends when the sidebar opens (RTE-064)."])
add("CON-046", ["VERIFIED geometry of the Topics view: names 18px black serif; descriptions 13px/18px #666 with plain blue links; a 22px #ededec round button with three dots; rows ruled. Rebuilt; deliberate difference: links in the descriptions keep an underline (live has colour alone, which fails WCAG 1.4.1)."])
json.dump(atlas, open(T / "features.json", "w"), ensure_ascii=False, indent=1)
atlas = json.load(open(T / "features.json")); by = {f["id"]: f for f in atlas}
add("SRC-048", ["VERIFIED geometry (1280px): tabs 22px Roboto (active black, others #666) with count pills; the sort control uses the up/down-arrows icon; the search box has a 26px magnifier and a plain 20px grey ×; the page column starts 64px down and the Filters module 142px down (aligned under the tabs); filter checkboxes are outlined 14px squares with a light tick. Rebuilt."])
json.dump(atlas, open(T / "features.json", "w"), ensure_ascii=False, indent=1)
atlas = json.load(open(T / "features.json")); by = {f["id"]: f for f in atlas}
add("LIB-008", ["VERIFIED geometry (1280px): page title 30px/500 black upper-case; part headings ('TORAH (The Five Books of Moses)') 18px grey serif, the parenthetical in the same style; block titles 24px on a 31.2px line; descriptions 14px on an 18px line; the About text in the sidebar 16px on its natural ~19px line (was 23px). Note: the live face for these is Adobe Garamond Pro (computed font-family 'adobe-garamond-pro'), Cardo here — owner decision pending, which is also why 'TANAKH' is 138px wide against 123px on the live page. Rebuilt for sizes and weights."])
json.dump(atlas, open(T / "features.json", "w"), ensure_ascii=False, indent=1)
atlas = json.load(open(T / "features.json")); by = {f["id"]: f for f in atlas}
add("SHL-074", ["Rebuild guard (found when the 15px version line made two subtitle lines taller than the bar): the text header is ALWAYS 60px — title on a 21px line, version/attribution lines 17px each — so choosing a version (which adds a line) never moves the text below it (e2e/about.spec.ts)."])
json.dump(atlas, open(T / "features.json", "w"), ensure_ascii=False, indent=1)
