# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-11-11 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopicPoolLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool', models.CharField(max_length=255)),
                ('topic_slug', models.CharField(max_length=255)),
            ],
        ),
    ]
