# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-11-11 18:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_tools', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopicPoolLink',
        ),
    ]
