# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-11-12 03:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_tools', '0003_topicpoollink'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='topicpoollink',
            unique_together=set([('pool', 'topic_slug')]),
        ),
    ]
