{{- if and .Values.authService.enabled .Values.authService.postgres.builtin }}
apiVersion: v1
kind: Secret
metadata:
  name: auth-service-pg-{{ .Values.deployEnv }}
  labels:
    deployEnv: "{{ .Values.deployEnv }}"
type: Opaque
stringData:
  POSTGRES_PASSWORD: "poc-{{ .Values.deployEnv }}-pw"
  AUTH_PG_DSN: "postgres://postgres:poc-{{ .Values.deployEnv }}-pw@auth-service-postgres-{{ .Values.deployEnv }}:5432/postgres?sslmode=disable"
{{- end }}
