{{- if .Values.backup.mongo.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: create-dumps-{{ .Values.deployEnv }}
  labels:
    deployEnv: "{{ .Values.deployEnv }}"
    {{- include "sefaria.labels" . | nindent 4 }}
data:
  create-dumps.sh: |-
    #!/usr/bin/env bash
    set -eo pipefail

    {{- if .Values.restore.dynamicName }}
    DATABASE="${SEFARIA_DB}-{{ .Values.deployEnv }}"
    {{- else }}
    DATABASE="${SEFARIA_DB}"
    {{- end }}

    if [[ -z "${MONGO_HOST:-}" ]]; then
      echo "Mongo Host not specified"
      exit 1
    fi

    URI="mongodb://"

    if [[ -n "${SEFARIA_DB_USER:-}" ]]; then
      URI="${URI}${SEFARIA_DB_USER}"
      if [[ -n "${SEFARIA_DB_PASSWORD:-}" ]]; then
          URI="${URI}:${SEFARIA_DB_PASSWORD}"
      fi
      URI="${URI}@"
    fi

    URI="${URI}${MONGO_HOST}/?ssl=false"

    if [[ -n "${SEFARIA_DB_USER:-}" ]]; then
      URI="${URI}&authSource=admin"
    fi

    if [[ -n "${MONGO_REPLICASET_NAME:-}" ]]; then
      URI="${URI}&replicaSet=${MONGO_REPLICASET_NAME}"
    fi

    DATADIR="/mongodumps/shared_volume"

    echo "Dumping database: ${DATABASE}"
    until mongodump --uri="$URI" -v -d "$DATABASE" \
      --excludeCollection=django_cache \
      --excludeCollection=user_history \
      --excludeCollection=history \
      --excludeCollection=linker_output \
      --excludeCollection=webpages_text \
      -o "${DATADIR}/dump"
    do
      echo "mongodump failed, retrying in 5s..."
      rm -rf "${DATADIR}/dump"
      sleep 5
    done

    echo "${DATABASE}" > "${DATADIR}/db_name.txt"

    {{- if .Values.backup.mongo.public }}
    echo "Dumping license-filtered texts for public variant"
    until mongodump --uri="$URI" -v -d "$DATABASE" \
      --collection texts \
      --query '{"license": {"$not": {"$regex": "^Copyright", "$options": "i"}}}' \
      -o "${DATADIR}/public_texts_dump"
    do
      echo "filtered texts dump failed, retrying in 5s..."
      rm -rf "${DATADIR}/public_texts_dump"
      sleep 5
    done
    {{- end }}

    echo "dump complete - upload should start"
{{- end }}
