# NB: This assumes an already-functioning mongo instance. 
# Parameters:
# MONGO_HOST: Mongo hostname
# SANDBOX_NAME: The name of the table created by this job
---
{{- if eq .Values.sandbox "true" }}
apiVersion: batch/v1
kind: Job
metadata:
  name: destroy-mongo-{{ .Values.deployEnv }}
  labels:
    deployEnv: {{ .Values.deployEnv | quote }}
    {{- include "sefaria.labels" . | nindent 4 }}
  annotations: 
    helm.sh/hook: post-delete
    helm.sh/hook-delete-policy: hook-succeeded
    helm.sh/hook-weight: "10"
spec:
  template:
    spec:
      containers:
      - name: mongo-destroy-{{ .Values.deployEnv }}
        image: mongo:4.4
        env:
          - name: MONGO_HOST
            value: {{ .Values.localSettings.MONGO_HOST | quote }}
          - name: SANDBOX_NAME
            value: {{ .Values.deployEnv }} 
        command: ["/script/destroy-mongo.sh"]
        volumeMounts:
        - name: script
          mountPath: /script
      restartPolicy: Never
      volumes:
      - name: script
        configMap:
          name: mongo-destroy-{{ .Values.deployEnv }}
          defaultMode: 0755
  ttlSecondsAfterFinished: 432000
{{- end }}
