# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-12-11 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonalTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Start date of when this will appear. End date is implied by when the next Seasonal Topic is displayed.')),
                ('display_start_date_israel', models.DateField(blank=True, null=True)),
                ('display_end_date_israel', models.DateField(blank=True, null=True)),
                ('display_start_date_diaspora', models.DateField(blank=True, null=True)),
                ('display_end_date_diaspora', models.DateField(blank=True, null=True)),
                ('display_date_prefix', models.CharField(blank=True, max_length=255, null=True)),
                ('display_date_suffix', models.CharField(blank=True, max_length=255, null=True)),
                ('lang', models.CharField(choices=[('en', 'English'), ('he', 'Hebrew')], max_length=2)),
            ],
            options={
                'verbose_name': 'Landing Page - Calendar',
                'verbose_name_plural': 'Landing Page - Calendar',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('slug', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('en_title', models.CharField(blank=True, default='', max_length=255)),
                ('he_title', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Topic Pool Management',
                'verbose_name_plural': 'Topic Pool Management',
            },
        ),
        migrations.CreateModel(
            name='TopicOfTheDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('lang', models.CharField(choices=[('en', 'English'), ('he', 'Hebrew')], max_length=2)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_of_the_day', to='django_topics.Topic')),
            ],
            options={
                'verbose_name': 'Landing Page - Topic of the Day',
                'verbose_name_plural': 'Landing Page - Topic of the Day',
            },
        ),
        migrations.CreateModel(
            name='TopicPool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='topic',
            name='pools',
            field=models.ManyToManyField(blank=True, related_name='topics', to='django_topics.TopicPool'),
        ),
        migrations.AddField(
            model_name='seasonaltopic',
            name='secondary_topic',
            field=models.ForeignKey(blank=True, help_text="Secondary topic which will be displayed alongside `topic`. E.g. `topic` is 'Teshuva' then secondary topic could be 'Yom Kippur'.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seasonal_secondary_topic', to='django_topics.Topic'),
        ),
        migrations.AddField(
            model_name='seasonaltopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonal_topic', to='django_topics.Topic'),
        ),
        migrations.CreateModel(
            name='SeasonalTopicEnglish',
            fields=[
            ],
            options={
                'verbose_name': 'Landing Page - Calendar (EN)',
                'verbose_name_plural': 'Landing Page - Calendar (EN)',
                'proxy': True,
                'indexes': [],
            },
            bases=('django_topics.seasonaltopic',),
        ),
        migrations.CreateModel(
            name='SeasonalTopicHebrew',
            fields=[
            ],
            options={
                'verbose_name': 'Landing Page - Calendar (HE)',
                'verbose_name_plural': 'Landing Page - Calendar (HE)',
                'proxy': True,
                'indexes': [],
            },
            bases=('django_topics.seasonaltopic',),
        ),
        migrations.CreateModel(
            name='TopicOfTheDayEnglish',
            fields=[
            ],
            options={
                'verbose_name': 'Landing Page - Topic of the Day (EN)',
                'verbose_name_plural': 'Landing Page - Topic of the Day (EN)',
                'proxy': True,
                'indexes': [],
            },
            bases=('django_topics.topicoftheday',),
        ),
        migrations.CreateModel(
            name='TopicOfTheDayHebrew',
            fields=[
            ],
            options={
                'verbose_name': 'Landing Page - Topic of the Day (HE)',
                'verbose_name_plural': 'Landing Page - Topic of the Day (HE)',
                'proxy': True,
                'indexes': [],
            },
            bases=('django_topics.topicoftheday',),
        ),
        migrations.AlterUniqueTogether(
            name='topicoftheday',
            unique_together=set([('topic', 'start_date')]),
        ),
        migrations.AlterUniqueTogether(
            name='seasonaltopic',
            unique_together=set([('topic', 'start_date')]),
        ),
    ]
