# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-11-18 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('en_title', models.CharField(blank=True, default='', max_length=255)),
                ('he_title', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TopicOfTheDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_of_the_day', to='django_topics.Topic')),
            ],
            options={
                'verbose_name': 'Topic of the Day',
                'verbose_name_plural': 'Topics of the Day',
            },
        ),
        migrations.CreateModel(
            name='TopicPool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='topic',
            name='pools',
            field=models.ManyToManyField(blank=True, related_name='topics', to='django_topics.TopicPool'),
        ),
        migrations.AlterUniqueTogether(
            name='topicoftheday',
            unique_together=set([('topic', 'start_date', 'end_date')]),
        ),
    ]
