# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-11-19 08:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonalTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('display_start_date_israel', models.DateField(blank=True, null=True)),
                ('display_end_date_israel', models.DateField(blank=True, null=True)),
                ('display_start_date_diaspora', models.DateField(blank=True, null=True)),
                ('display_end_date_diaspora', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Seasonal Topic',
                'verbose_name_plural': 'Seasonal Topics',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                # ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('en_title', models.CharField(blank=True, default='', max_length=255)),
                ('he_title', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TopicOfTheDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_of_the_day', to='django_topics.Topic')),
            ],
            options={
                'verbose_name': 'Topic of the Day',
                'verbose_name_plural': 'Topics of the Day',
            },
        ),
        migrations.CreateModel(
            name='TopicPool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='topic',
            name='pools',
            field=models.ManyToManyField(blank=True, related_name='topics', to='django_topics.TopicPool'),
        ),
        migrations.AddField(
            model_name='seasonaltopic',
            name='secondary_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seasonal_secondary_topic', to='django_topics.Topic'),
        ),
        migrations.AddField(
            model_name='seasonaltopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonal_topic', to='django_topics.Topic'),
        ),
        migrations.AlterUniqueTogether(
            name='topicoftheday',
            unique_together=set([('topic', 'start_date')]),
        ),
        migrations.AlterUniqueTogether(
            name='seasonaltopic',
            unique_together=set([('topic', 'start_date')]),
        ),
    ]
