# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-11-21 10:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_topics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seasonaltopic',
            options={'verbose_name': 'Landing Page - Calendar', 'verbose_name_plural': 'Landing Page - Calendar'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Topic Pool Management', 'verbose_name_plural': 'Topic Pool Management'},
        ),
        migrations.AlterModelOptions(
            name='topicoftheday',
            options={'verbose_name': 'Landing Page - Topic of the Day', 'verbose_name_plural': 'Landing Page - Topic of the Day'},
        ),
        migrations.AlterField(
            model_name='seasonaltopic',
            name='secondary_topic',
            field=models.ForeignKey(blank=True, help_text="Secondary topic which will be displayed alongside `topic`. E.g. `topic` is 'Teshuva' then secondary topic could be 'Yom Kippur'.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seasonal_secondary_topic', to='django_topics.Topic'),
        ),
        migrations.AlterField(
            model_name='seasonaltopic',
            name='start_date',
            field=models.DateField(help_text='Start date of when this will appear. End date is implied by when the next Seasonal Topic is displayed.'),
        ),
    ]
