# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-11-13 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='pools',
            field=models.ManyToManyField(blank=True, related_name='topics', to='topics.TopicPool'),
        ),
    ]
