# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-11-21 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_topics', '0002_auto_20241121_0617'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='topic',
        #     name='id',
        # ),
        # migrations.AlterField(
        #     model_name='topic',
        #     name='slug',
        #     field=models.CharField(max_length=255, primary_key=True, serialize=False),
        # ),
    ]
