# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-11-27 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_topics', '0006_seasonaltopicenglish_seasonaltopichebrew'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicOfTheDayEnglish',
            fields=[
            ],
            options={
                'verbose_name': 'Landing Page - Topic of the Day (EN)',
                'verbose_name_plural': 'Landing Page - Topic of the Day (EN)',
                'proxy': True,
                'indexes': [],
            },
            bases=('django_topics.topicoftheday',),
        ),
        migrations.CreateModel(
            name='TopicOfTheDayHebrew',
            fields=[
            ],
            options={
                'verbose_name': 'Landing Page - Topic of the Day (HE)',
                'verbose_name_plural': 'Landing Page - Topic of the Day (HE)',
                'proxy': True,
                'indexes': [],
            },
            bases=('django_topics.topicoftheday',),
        ),
        migrations.AlterModelOptions(
            name='seasonaltopicenglish',
            options={'verbose_name': 'Landing Page - Calendar (EN)', 'verbose_name_plural': 'Landing Page - Calendar (EN)'},
        ),
        migrations.AlterModelOptions(
            name='seasonaltopichebrew',
            options={'verbose_name': 'Landing Page - Calendar (HE)', 'verbose_name_plural': 'Landing Page - Calendar (HE)'},
        ),
        migrations.AddField(
            model_name='topicoftheday',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('he', 'Hebrew')], default='en', max_length=2),
            preserve_default=False,
        ),
    ]
