# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-12-15 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_topics', '0006_seasonaltopicenglish_seasonaltopichebrew'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('lang', models.CharField(choices=[('en', 'English'), ('he', 'Hebrew')], max_length=2)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_topic', to='django_topics.Topic')),
            ],
            options={
                'verbose_name': 'Landing Page - Featured Topic',
                'verbose_name_plural': 'Landing Page - Featured Topic',
            },
        ),
        migrations.AlterUniqueTogether(
            name='topicoftheday',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='topicoftheday',
            name='topic',
        ),
        migrations.AlterModelOptions(
            name='seasonaltopicenglish',
            options={'verbose_name': 'Landing Page - Calendar (EN)', 'verbose_name_plural': 'Landing Page - Calendar (EN)'},
        ),
        migrations.AlterModelOptions(
            name='seasonaltopichebrew',
            options={'verbose_name': 'Landing Page - Calendar (HE)', 'verbose_name_plural': 'Landing Page - Calendar (HE)'},
        ),
        migrations.DeleteModel(
            name='TopicOfTheDay',
        ),
        migrations.CreateModel(
            name='FeaturedTopicEnglish',
            fields=[
            ],
            options={
                'verbose_name': 'Landing Page - Featured Topic (EN)',
                'verbose_name_plural': 'Landing Page - Featured Topic (EN)',
                'proxy': True,
                'indexes': [],
            },
            bases=('django_topics.featuredtopic',),
        ),
        migrations.CreateModel(
            name='FeaturedTopicHebrew',
            fields=[
            ],
            options={
                'verbose_name': 'Landing Page - Featured Topic (HE)',
                'verbose_name_plural': 'Landing Page - Featured Topic (HE)',
                'proxy': True,
                'indexes': [],
            },
            bases=('django_topics.featuredtopic',),
        ),
        migrations.AlterUniqueTogether(
            name='featuredtopic',
            unique_together=set([('topic', 'start_date')]),
        ),
    ]
