# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-12-17 11:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_topics', '0007_auto_20241127_0034'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopicOfTheDayEnglish',
        ),
        migrations.DeleteModel(
            name='TopicOfTheDayHebrew',
        ),
        migrations.CreateModel(
            name='FeaturedTopicEnglish',
            fields=[
            ],
            options={
                'verbose_name': 'Landing Page - Featured Topic (EN)',
                'verbose_name_plural': 'Landing Page - Featured Topic (EN)',
                'proxy': True,
                'indexes': [],
            },
            bases=('django_topics.topicoftheday',),
        ),
        migrations.CreateModel(
            name='FeaturedTopicHebrew',
            fields=[
            ],
            options={
                'verbose_name': 'Landing Page - Featured Topic (HE)',
                'verbose_name_plural': 'Landing Page - Featured Topic (HE)',
                'proxy': True,
                'indexes': [],
            },
            bases=('django_topics.topicoftheday',),
        ),
        migrations.AlterModelOptions(
            name='topicoftheday',
            options={'verbose_name': 'Landing Page - Featured Topic', 'verbose_name_plural': 'Landing Page - Featured Topic'},
        ),
    ]
