# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-02-10 10:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_topics', '0008_auto_20241217_0702'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='topicoftheday',
            unique_together=set([('topic', 'start_date', 'lang')]),
        ),
    ]
