# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-02-16 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_topics', '0009_auto_20250210_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='seasonaltopic',
            unique_together=set([('topic', 'start_date', 'lang')]),
        ),
    ]
