# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-09-18 07:58
from __future__ import unicode_literals

from django.db import migrations


def revert_voices_to_sheets(apps, schema_editor):
    """Revert the change: rename 'voices' pool back to 'sheets'."""
    TopicPool = apps.get_model('django_topics', 'TopicPool')
    
    try:
        voices_pool = TopicPool.objects.get(name='voices')
        voices_pool.name = 'sheets'
        voices_pool.save()
        print("Successfully reverted 'voices' pool back to 'sheets'")
    except TopicPool.DoesNotExist:
        print("No 'voices' pool found to revert")


class Migration(migrations.Migration):

    dependencies = [
        ('django_topics', '0012_rename_sheets_pool_to_voices'),
    ]

    operations = [
        ## This migration is no longer needed because we have commented out the rename_sheets_to_voices migration.
        ## migrations.RunPython(revert_voices_to_sheets, migrations.RunPython.noop),
    ]
