name: Add Coolify Preview to Shortcut

on:
  pull_request:
    types: [opened]

jobs:
  update-shortcut:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Shortcut Story ID from Branch Name
        id: extract_story
        run: |
          STORY_ID=$(echo "${{ github.event.pull_request.head.ref }}" | grep -oE 'sc-[0-9]+' | grep -oE '[0-9]+')
          echo "Extracted Story ID: $STORY_ID"
          echo "STORY_ID=$STORY_ID" >> $GITHUB_ENV

      - name: Verify Story ID Extraction
        run: |
          echo "Extracted Shortcut Story ID: $STORY_ID"

      - name: Add Coolify Preview URL to Shortcut
        if: env.STORY_ID != ''
        run: |
          curl -X POST "https://api.app.shortcut.com/api/v3/stories/$STORY_ID/comments" \
               -H "Content-Type: application/json" \
               -H "Shortcut-Token: ${{ secrets.SHORTCUT_API_TOKEN }}" \
               -d '{
                 "text": "🚀 Preview Environment: [View Here](http://${{ github.event.pull_request.number }}.coolifydev.sefaria.org)"
               }'
